<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manager Menu</name>
   <tag></tag>
   <elementGuidId>5f97df8a-6692-47e3-aeaf-b59d5a418f51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[text() = &quot;${ManagerMenu}&quot;]/img[@id=&quot;imgError&quot;][count(. | //*[@tabindex = '0']) = count(//*[@tabindex = '0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane_']/ul/li/ul/li/span[text()=&quot;${ManagerMenu}&quot;]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06e5a853-08bd-4e25-b664-a84cef7c0357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e2b2e6c-f576-411b-99bd-dea90355f2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgError</value>
      <webElementGuid>eaf3360e-8ad6-436f-8576-3bf547b23b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/menu/menu_down.gif</value>
      <webElementGuid>039d3f23-a9a8-4ae4-ab14-9142e71e1f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[text() = &quot;${ManagerMenu}&quot;]/img[@id=&quot;imgError&quot;]</value>
      <webElementGuid>07342400-0d10-41de-92cb-f2ad3304d0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul/li/ul/li/span/img</value>
      <webElementGuid>33e09769-393c-4445-ad26-b9398fcb950d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='imgError'])[5]</value>
      <webElementGuid>d9b5ff0f-d48c-4d8c-b444-a403e312b0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/img</value>
      <webElementGuid>60a2f029-3435-49ee-9bf9-26e032f6231f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgError' and @src = '../plaf/images/default/menu/menu_down.gif']</value>
      <webElementGuid>3427505a-15ce-45b8-a10a-b1450e52ed23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
