<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - IDs Presented</name>
   <tag></tag>
   <elementGuidId>fbbfa5d5-dd9e-4fdb-a658-2a2cd0d636c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:LEGAL.DOC.NAME:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b59d04b-fa28-49d5-8242-825c89c1e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>3058c878-8848-473c-b07d-4ad02f71be1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:LEGAL.DOC.NAME:1</value>
      <webElementGuid>98f394df-5dc7-4ea1-a24c-685414ea4820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:LEGAL.DOC.NAME:1</value>
      <webElementGuid>db23d0b4-e5e1-435b-92db-8c6534171a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f8ce974-a191-413f-aa41-d3b3245b6b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab4</value>
      <webElementGuid>016f0e9d-c244-4d4b-84b8-9b81b2d91b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>ACR</value>
      <webElementGuid>32e0aad4-d855-4c6d-8d04-fd2370065b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>d54bfb48-7003-448d-9025-51772f108de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>e1623562-63c0-4877-8fff-32435cb3eef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_LEGAL.DOC.NAME:1</value>
      <webElementGuid>50b34012-3fd7-4d5e-93c7-e728d78e6c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'LEGAL.DOC.NAME');</value>
      <webElementGuid>4c24f4e4-350c-440a-a4d9-b18c65f7660c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('LEGAL.DOC.NAME')</value>
      <webElementGuid>3db6e7d6-026e-4e7b-ace4-42d389a72cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id</value>
      <webElementGuid>de020c0b-5dd0-4338-9561-e0fb37a1daff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:LEGAL.DOC.NAME:1&quot;)</value>
      <webElementGuid>b7b06d05-e02b-48fb-aba1-a1e254f82677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer IND/Address_Tab/frame_Capture object_VERAMEND100455493601</value>
      <webElementGuid>4d2fbf97-2e6e-402b-a7a7-1b109d90d6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab4']/tbody/tr[5]/td[3]/select</value>
      <webElementGuid>f6e3bace-ba67-409f-aa02-f9c42534e1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:LEGAL.DOC.NAME:1']</value>
      <webElementGuid>e7b0900a-874b-4b60-8979-ee28feb009ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDs Presented.1'])[1]/following::select[1]</value>
      <webElementGuid>4c172afa-f347-415c-9ad1-cfdcc7d18718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number.1'])[1]/following::select[1]</value>
      <webElementGuid>8f639fe9-e1bd-4a1c-8810-aceeff7a95c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue Date.1'])[1]/preceding::select[1]</value>
      <webElementGuid>1897f8a2-c336-49c7-b4a7-7af5201c3bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry Date.1'])[1]/preceding::select[1]</value>
      <webElementGuid>bf76fb08-ece8-45f9-868d-73a466e0cbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/select</value>
      <webElementGuid>3e709383-3fe0-4210-b4fd-44f72a68d048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:LEGAL.DOC.NAME:1' and @id = 'fieldName:LEGAL.DOC.NAME:1' and (text() = '  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id' or . = '  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id')]</value>
      <webElementGuid>e3639d62-e6c9-4145-821e-23339cbbe081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
