<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Source of Funds</name>
   <tag></tag>
   <elementGuidId>6882d449-99fc-49f1-909a-d92132835a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6487aefd-d79d-4013-b37d-01498dad4028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>59f16a29-9ddf-4490-acdb-f821929adbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>7e1e0960-a7c1-487c-9b94-ec774dacd949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>142a0e3a-4df1-4bec-a3fb-262ce591a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f136d683-467c-477f-8748-912e2acaed5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab6</value>
      <webElementGuid>538f52e8-69e4-4100-97a4-a91af6ca09d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>783609d3-bd6b-41db-a5ba-2abd11954818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>72b7e5e8-17b6-4d87-b8ba-ce83eb9f456b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>1cc2e85a-aff9-4ee9-ab28-f9ae21918845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SOURCE.OF.FUNDS:1</value>
      <webElementGuid>f7ac587c-1617-475d-8ec9-e85948865ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SOURCE.OF.FUNDS');</value>
      <webElementGuid>ee3b6df6-9547-4f80-a099-eae15b834e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SOURCE.OF.FUNDS')</value>
      <webElementGuid>b7ecab3c-1673-44f0-a2f7-b94112fecb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus</value>
      <webElementGuid>2da03fa7-463c-4254-b030-8dd0be47af34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SOURCE.OF.FUNDS:1&quot;)</value>
      <webElementGuid>a837bd3f-6cdc-4542-9948-d2de7cf9c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer IND/Address_Tab/frame_Capture object_VERAMEND100455493601</value>
      <webElementGuid>549435f0-e7e9-47b1-b255-04cb08b684cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab6']/tbody/tr/td[3]/select</value>
      <webElementGuid>2e2af79a-ba31-47cb-afe7-cad898cb3ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      <webElementGuid>10996fdf-ee05-473f-a899-87c5b202dbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[1]/following::select[1]</value>
      <webElementGuid>1f3e05f6-4acc-4c5b-a21e-6bedf2111c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office.1'])[1]/following::select[1]</value>
      <webElementGuid>039e919e-81b2-4672-8fd2-f2c038aec7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status.1'])[1]/preceding::select[1]</value>
      <webElementGuid>8e9130e2-1a63-410e-96d8-c11693e41182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer/Business Name.1'])[1]/preceding::select[2]</value>
      <webElementGuid>2f900b4c-3a59-4fe2-9d15-38f1e1359d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr/td[3]/select</value>
      <webElementGuid>23b047e4-1819-46cb-9557-a85e85879515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:SOURCE.OF.FUNDS:1' and @id = 'fieldName:SOURCE.OF.FUNDS:1' and (text() = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus' or . = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus')]</value>
      <webElementGuid>126c53dd-9785-486f-a46f-288816942349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
