<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Employment Status</name>
   <tag></tag>
   <elementGuidId>11e68f92-f0ee-4ddb-b20c-1afc20eefc7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:EMPLOYMENT.STATUS:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>709f5d48-4679-4ed3-a1df-b05ee2b4a5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>6e7eb989-0594-46a1-a2e5-08dee47ac4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:EMPLOYMENT.STATUS:1</value>
      <webElementGuid>c56401a4-8793-4308-a0c8-cea403c95d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:EMPLOYMENT.STATUS:1</value>
      <webElementGuid>6657eff7-5b30-40b2-8f62-39cedebb8e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b14b4bf1-ffcf-4642-9a0b-995c6704a725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab6</value>
      <webElementGuid>22f544bc-33da-45e9-b0a8-cf19b38b2019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>DEPED.MBHTE.APDS</value>
      <webElementGuid>c3223ae8-addc-415d-b544-42159ddb0d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>370ddcb8-45b8-4531-8fa8-fd2b3b33b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>427d7082-a322-4084-9663-0718d6e96e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_EMPLOYMENT.STATUS:1</value>
      <webElementGuid>5bd60ef7-cc7c-4095-a677-7a3215fe9a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'EMPLOYMENT.STATUS');</value>
      <webElementGuid>cb4b26f9-154c-4141-9ea0-90e6d6d5e90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('EMPLOYMENT.STATUS')</value>
      <webElementGuid>8a417168-c781-4a81-b026-589e1abbba1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private</value>
      <webElementGuid>fa87de75-c466-43a2-81d1-01aa65812eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:EMPLOYMENT.STATUS:1&quot;)</value>
      <webElementGuid>3ad4c5c4-160b-40d8-be42-4f34d0adf147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer IND/Address_Tab/frame_Capture object_VERAMEND100455493601</value>
      <webElementGuid>87394612-3656-4f83-896f-1af7ef625ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab6']/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>179465a5-fc0d-47c0-bcf3-ff69b6b091ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:EMPLOYMENT.STATUS:1']</value>
      <webElementGuid>23b2d65e-73a6-4176-9258-f3a35efec276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status.1'])[1]/following::select[1]</value>
      <webElementGuid>d54e2a46-f48d-44e7-a4e0-f018b5b1f9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[1]/following::select[2]</value>
      <webElementGuid>9fb35652-9fca-4a8f-a067-96417cd0d42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer/Business Name.1'])[1]/preceding::select[1]</value>
      <webElementGuid>dc3d5d1a-76ad-4f8a-96c2-2612ba652ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer Address.1.1'])[1]/preceding::select[1]</value>
      <webElementGuid>528f3116-3c0f-4880-ab4f-9169594e2878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>0d191492-238a-4980-80f0-20eee1a752de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:EMPLOYMENT.STATUS:1' and @id = 'fieldName:EMPLOYMENT.STATUS:1' and (text() = '  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private' or . = '  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private')]</value>
      <webElementGuid>851681ed-aa6c-4a2c-80a2-9d829d3af8d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
