<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find</name>
   <tag></tag>
   <elementGuidId>4ec4b00b-285f-4ebb-a335-33039404e63c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='doHighlight(this);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.textbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aebccf1e-2799-4629-adfa-b218b405d570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Run Selection</value>
      <webElementGuid>f009b326-07e9-4d10-ac53-cc3a67246346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Run Selection</value>
      <webElementGuid>4eecabe6-f612-4b14-ad4e-f5bdcac7f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbtn</value>
      <webElementGuid>e3d60aca-0fee-49ac-9393-f134697aac94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>ed085843-7e77-4313-a1ee-d9e2154abb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>a770b4e1-d21e-46e8-8c3e-8ec914c173ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:
						   toggleStateButton();doEnquiry()</value>
      <webElementGuid>e0190988-9255-4827-9065-c313aa5262fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doHighlight(this);</value>
      <webElementGuid>2fc59a47-c223-4f1a-913c-8cb714d95ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find</value>
      <webElementGuid>a46f0bfa-56c5-4a84-a3cb-235af1574782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqsel_workarea100154929303&quot;)/table[@class=&quot;enqsel-main enqsel-main_EWBS3AAFINDARRANGEMENTAD&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;display_box display_box_EWBS3AAFINDARRANGEMENTAD enqsel-selections enqsel-selections_EWBS3AAFINDARRANGEMENTAD&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;header-table header-table_EWBS3AAFINDARRANGEMENTAD&quot;]/tbody[1]/tr[@class=&quot;caption caption_EWBS3AAFINDARRANGEMENTAD&quot;]/td[3]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;textbtn&quot;]</value>
      <webElementGuid>365b5b81-d952-4c50-a67e-c0fa5b590487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enqsel_workarea100154929303']/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td[3]/div/table/tbody/tr/td/a</value>
      <webElementGuid>572640be-a621-46de-b1d8-0a2378b095c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='doHighlight(this);']</value>
      <webElementGuid>b08f47cf-dbec-412e-996f-07c2c3ee1454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find')]</value>
      <webElementGuid>574abc5c-a333-4c04-b9fd-8f72a0fff987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Selection'])[1]/following::a[1]</value>
      <webElementGuid>b35b63f0-59fd-4471-b5ef-96aac9627b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[1]/following::a[2]</value>
      <webElementGuid>9dd987c4-6057-4421-8949-1fa4ad530075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::a[1]</value>
      <webElementGuid>6f9e5f54-0427-479b-92aa-9ff93cec274d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find']/parent::*</value>
      <webElementGuid>8261e307-a3bd-474a-a569-d7f4b3808ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:
						   toggleStateButton();doEnquiry()')]</value>
      <webElementGuid>386a500f-0abd-450b-974b-2041ef311296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/a</value>
      <webElementGuid>abacbab1-ff4d-45f9-b8d0-e5f926ebfafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@alt = 'Run Selection' and @title = 'Run Selection' and @href = 'javascript:
						   toggleStateButton();doEnquiry()' and (text() = 'Find' or . = 'Find')]</value>
      <webElementGuid>f067664f-3a1f-4620-90a6-50d0de9d460d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
