<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arrangement_New Activity</name>
   <tag></tag>
   <elementGuidId>3c00ee34-1c58-4afc-9eff-4502491d5e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'New Activity')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.enqDrillLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cb01a9c-de94-4be8-8980-ca08c66445b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqDrillLink</value>
      <webElementGuid>4e579098-705c-47c1-a085-cfc8c5c5e592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:drilldown('1','1_1')</value>
      <webElementGuid>0a758aeb-ae21-49cf-8597-cb94e8138de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2452bd01-6380-4b35-a510-a941e128e140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Activity</value>
      <webElementGuid>8666449e-e0f9-4075-bb98-ef84e0943d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1_Heading066984150800&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_AAOVERVIEWHEADINGLIVAD&quot;]/a[@class=&quot;enqDrillLink&quot;]</value>
      <webElementGuid>2e4d84ec-90fa-41b6-bc64-325b43bbe766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1_Heading066984150800']/td[2]/a</value>
      <webElementGuid>c293eb40-f37c-4e4d-b91e-133a7178fd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Activity')]</value>
      <webElementGuid>1b829b1d-5c8e-409f-816b-9f83b57e6ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrangement Overview - Deposits'])[1]/following::a[1]</value>
      <webElementGuid>d52152fb-1af9-4634-9fa6-8e69d82d70e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrangement'])[1]/preceding::a[1]</value>
      <webElementGuid>f96be3c3-8dca-4a09-9fd9-0eda25ff047d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA23198K76CP'])[1]/preceding::a[1]</value>
      <webElementGuid>c686017a-23a4-4cbe-be25-632388beba4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Activity']/parent::*</value>
      <webElementGuid>f4e58ac0-ee98-46d7-9631-bf521fc3ae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:drilldown('1','1_1')&quot;)]</value>
      <webElementGuid>70a71c8a-62f7-479e-9d6e-bc3c0bdcc4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f75e737d-732d-482f-8575-0b15f8fc8468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:drilldown(&quot; , &quot;'&quot; , &quot;1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1_1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'New Activity' or . = 'New Activity')]</value>
      <webElementGuid>d21a6526-f7c7-4d99-b4e3-f93b74d4ff30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
