<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_View</name>
   <tag></tag>
   <elementGuidId>df61b6fd-025e-46cc-801b-da9a3a845cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Overview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Overview&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd45b4ae-aeb1-44cc-8ee1-cd43291da46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/enquiry/drilldown/view.gif</value>
      <webElementGuid>fdbaab13-1a40-494c-a2bd-1a614d6017c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>8e76faaa-0f5a-4e1e-ba34-d6c83762e8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>f57d78d8-39ed-477e-9a8f-ffc4646f1503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1_workarea100154929303&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_EWBS3AAFINDARRANGEMENTAD&quot;]/a[1]/img[1]</value>
      <webElementGuid>cb83a4fc-c72f-4e15-a412-608285ef3326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1_workarea100154929303']/td[7]/a/img</value>
      <webElementGuid>7e4ac43b-a094-4def-ae3b-ec0164a50bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Overview']</value>
      <webElementGuid>1d67bbe6-bd1b-4169-b1c8-0b23a8c849e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/img</value>
      <webElementGuid>5e3183d2-0689-493f-b577-9bb867fe04db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/enquiry/drilldown/view.gif' and @alt = 'Overview' and @title = 'Overview']</value>
      <webElementGuid>d2459474-b290-4040-b6fa-26c34cb0c995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
