<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Check</name>
   <tag></tag>
   <elementGuidId>f37e0b9f-7ca6-4138-8eb5-c81e35c95875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Select Drilldown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Select Drilldown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c68cf42a-2292-482f-a3d4-8f731f5160c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Select Drilldown</value>
      <webElementGuid>d0686cd0-109f-4401-a5ec-c43cef2dbacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/menu/go.gif</value>
      <webElementGuid>e319caab-2ea8-4ce4-a322-fafb4dcaa942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1_Pending100074905200&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_AADETAILSACTIVITYLOGPENDINGFIN&quot;]/table[1]/tbody[1]/tr[@class=&quot;enqdrilldowncell enqdrilldowncell_AADETAILSACTIVITYLOGPENDINGFIN&quot;]/td[2]/a[@class=&quot;iconLink&quot;]/img[1]</value>
      <webElementGuid>be5e11dc-4918-4d0b-8d1e-8e0c6d2847e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1_Pending100074905200']/td[6]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>21714c27-1ef0-4e05-bf63-6fe77da4ab7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Select Drilldown']</value>
      <webElementGuid>c284547b-265c-4ea2-af9d-e814fc7a4c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>779635fe-b3c5-44d7-a7ad-b589a524dbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Select Drilldown' and @src = '../plaf/images/default/menu/go.gif']</value>
      <webElementGuid>b85be27e-9b78-4bc6-b73c-e9c9f84b106e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
