<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Source of Funds - Personal Savings</name>
   <tag></tag>
   <elementGuidId>cc2eb9a3-27d5-431b-9bd1-cab7bf439dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdc2c3db-fadf-4457-a40f-f0adaa6d431a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>2a8e3dc0-ddfa-42c8-8af5-a9482c23e403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>3b62bced-bce9-40ff-9daa-175de82385e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>27961f17-71dc-4d2d-a483-8e3152c8709b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c190f1d-19fe-4e0a-8047-bc2270842ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab6</value>
      <webElementGuid>19c9bbe4-fda3-4b48-bca4-98ccf9b590b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>43ae8713-b7ee-43a2-b43d-7fa341f5afe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>36153967-101e-4dcb-8088-087d8740fb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SOURCE.OF.FUNDS:1</value>
      <webElementGuid>094a1b00-0036-4ff6-a06c-375cb14ef661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SOURCE.OF.FUNDS');</value>
      <webElementGuid>a3588f22-cef9-4c4c-9b2d-f929bf7931c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SOURCE.OF.FUNDS')</value>
      <webElementGuid>ac0fe60e-8e27-4f85-bc9f-b91b7ff6f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus</value>
      <webElementGuid>94e4f598-ddbd-4fec-bc87-62311800c51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SOURCE.OF.FUNDS:1&quot;)</value>
      <webElementGuid>64d348c9-624c-46cf-9613-ee93a62dc5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab6']/tbody/tr/td[3]/select</value>
      <webElementGuid>17251d0b-b1dc-492e-a262-97087fec41be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      <webElementGuid>d31cfa3b-3272-4a84-98ee-3debd6ee978e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[1]/following::select[1]</value>
      <webElementGuid>8d7491df-8d51-4a5d-9ed0-bfdcec96f4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office.1'])[1]/following::select[1]</value>
      <webElementGuid>ce6b3d03-46c2-4d39-bec1-633e5ac01c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status.1'])[1]/preceding::select[1]</value>
      <webElementGuid>e79b1f1c-9ff8-4d60-ab76-10936f8b22d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer/Business Name.1'])[1]/preceding::select[2]</value>
      <webElementGuid>0e8439ea-311a-494f-bf67-15f1597149d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr/td[3]/select</value>
      <webElementGuid>4f69d29c-d034-405c-bc24-f01e7ec37248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:SOURCE.OF.FUNDS:1' and @id = 'fieldName:SOURCE.OF.FUNDS:1' and (text() = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus' or . = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus')]</value>
      <webElementGuid>ef29c60a-6f85-4951-b4a6-76d1518566f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
