<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Employment Status - Deped Mbhte - Apds</name>
   <tag></tag>
   <elementGuidId>56dd9cdb-5559-41fc-bc46-9ec5442c1bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:EMPLOYMENT.STATUS:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>887d82d0-4d30-406f-ad18-f9729bcb27c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>41938c12-3a6b-47bf-b762-09e5faeab3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:EMPLOYMENT.STATUS:1</value>
      <webElementGuid>eb825ebc-b69b-4015-8040-b132d12b3095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:EMPLOYMENT.STATUS:1</value>
      <webElementGuid>1996c6e9-9691-4275-b35e-e78b209efb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>588bb386-33d7-4d5d-8d7c-68c0b23a945b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab6</value>
      <webElementGuid>fb4b4259-8083-4fe7-922f-22d9d56cb5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>953e558e-923d-414b-b52e-e931bc8375bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>ef4188a4-0db7-4db7-bc53-9b92cc61b330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_EMPLOYMENT.STATUS:1</value>
      <webElementGuid>d9406764-400d-4bc9-a398-75bff81598fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'EMPLOYMENT.STATUS');</value>
      <webElementGuid>b4bf4dbd-580d-4819-bab6-a0a7ad1bc25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('EMPLOYMENT.STATUS')</value>
      <webElementGuid>b96437c5-5e0b-48fa-90e9-b2f4da387cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private</value>
      <webElementGuid>f74c2043-98c1-490f-892c-16ca98999848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:EMPLOYMENT.STATUS:1&quot;)</value>
      <webElementGuid>6829c037-96a1-4c86-998b-b8d41d8e97e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab6']/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>90df2d09-e58f-4829-8454-609e976d6785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:EMPLOYMENT.STATUS:1']</value>
      <webElementGuid>b8e34b60-84d3-44ca-92d7-3cb3079ea666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status.1'])[1]/following::select[1]</value>
      <webElementGuid>abdaeb9f-49a4-4921-b633-2aeb513b7fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[1]/following::select[2]</value>
      <webElementGuid>ec9a5979-acd4-4a69-b33d-73d2b7a772c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer/Business Name.1'])[1]/preceding::select[1]</value>
      <webElementGuid>04bbc237-6640-4dc1-a14c-bad468361b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer Address.1.1'])[1]/preceding::select[1]</value>
      <webElementGuid>42c3bc01-c022-492c-934b-a94c00be58c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>4b32bd64-e4d6-418d-9b77-234620227dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:EMPLOYMENT.STATUS:1' and @id = 'fieldName:EMPLOYMENT.STATUS:1' and (text() = '  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private' or . = '  Deped Mbhte - ApdsDeped - ApdsDeped - FasDeped - Newly Hired (Apds)Deped - Newly Hired (Fas)EmployerUnemployed - OthersPrevious EmploymentUnemployment - RetireeSelf-employedUnemployed - StudentUnpaid Family WorkerWage &amp; Salary Worker - GovernmentWage &amp; Salary Worker - OcwWage &amp; Salary Worker - Private')]</value>
      <webElementGuid>44467690-7a7d-478f-a265-300d061582b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
