<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputMiddleName</name>
   <tag></tag>
   <elementGuidId>c08bb721-3e07-4973-9b6a-4a1468b0559d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:L.MIDDLE.NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fce3272-4ec5-498f-bebb-c7ae8014962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b8ad6a1f-9b3b-48a4-8566-8a4e95f29c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>8b2b6b80-0bd8-4ff1-9e94-698b7764f4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.MIDDLE.NAME</value>
      <webElementGuid>cef2a539-93dd-47c9-99cd-cdbbb6948583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.MIDDLE.NAME</value>
      <webElementGuid>be84b6b7-d173-4796-9195-939aa61125d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>aad94986-0c8e-44f2-8f21-db394a0a37a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TESTING</value>
      <webElementGuid>296b2c78-b0f2-4d1a-b515-ac1814d6ee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>TESTING</value>
      <webElementGuid>04b37bcc-56dd-4ef3-9b37-6065534715a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUTV2</value>
      <webElementGuid>3be40248-4355-4406-a2b8-67f331cfe662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>eb959e4e-3569-475d-b08a-4c1149609638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d111c45c-b86b-4f61-9da5-2e39885388fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>6cdb45ed-2f3d-43a7-bd25-7ac0ed7a939e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hot</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>9a93986f-943b-476e-bff0-04559bc66643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cba9edb2-3674-4015-a760-545b76475c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>e8cba523-f4b9-43d7-a6d7-ae6a3b6dfd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.MIDDLE.NAME');</value>
      <webElementGuid>5b399031-7f75-437a-9c18-fd97bcf1dbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event); doFieldChangeEvent(event);</value>
      <webElementGuid>c707b3af-03d5-409c-a9b9-3a1c6c51f314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.MIDDLE.NAME')</value>
      <webElementGuid>d34cb915-6e74-44be-a3cf-4484558edf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.MIDDLE.NAME&quot;)</value>
      <webElementGuid>7dbfc3ed-6977-4b7a-86e5-ba0a0ff44c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>9473df81-2571-41eb-8b6c-d66fe51057fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:L.MIDDLE.NAME']</value>
      <webElementGuid>b3589c60-7958-44c3-9cd6-eb8be454e375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/input</value>
      <webElementGuid>2d1f1d95-d208-475f-8b2c-3da700e73de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:L.MIDDLE.NAME' and @name = 'fieldName:L.MIDDLE.NAME' and @type = 'text']</value>
      <webElementGuid>ed627d3c-e7f2-43b2-a7dc-fe547fcde592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
