<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSCORE-00054 - Search via Customer Number</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>87ee195f-85b7-4b1b-b6a3-332265ee4468</testSuiteGuid>
   <testCaseLink>
      <guid>6fab5e15-9cfa-4203-848c-422d1f9761b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9707b92d-19a2-4ab4-a158-62c5877e1cf7</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9707b92d-19a2-4ab4-a158-62c5877e1cf7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9707b92d-19a2-4ab4-a158-62c5877e1cf7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9707b92d-19a2-4ab4-a158-62c5877e1cf7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c42176d-3779-443c-9b9d-39b1a2619c62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9628a158-3691-4740-8eb8-a890fa8d450b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a0f16d66-b0c0-4ef6-a9fa-210898f82f91</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-5</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a0f16d66-b0c0-4ef6-a9fa-210898f82f91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c176835-a616-46cc-93eb-3028adbccf64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/515/Customer/TC_CUS S</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84bed49e-86ff-4a4e-9a62-ae77ce55abfc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Search Via CIF</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f47d2091-cc41-49c4-ae90-0b6a8bb8e4e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84bed49e-86ff-4a4e-9a62-ae77ce55abfc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CIF</value>
         <variableId>7f207ecc-7b15-404a-a00f-179ddcb586ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb6ca5be-f627-4f46-837f-6e29916a8120</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
