<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSCORE-00012 - Reprint Passbook</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ab5ef6a5-1918-4f24-a655-2c2244c0fcdf</testSuiteGuid>
   <testCaseLink>
      <guid>d9631e4c-4e59-43eb-804c-8c32a7dfe79c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5f177fbe-18dd-43f1-95ee-6a4c6d4688fe</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5f177fbe-18dd-43f1-95ee-6a4c6d4688fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f177fbe-18dd-43f1-95ee-6a4c6d4688fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f177fbe-18dd-43f1-95ee-6a4c6d4688fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c53e722-e86b-4df7-8fab-0fc886692891</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4ed4785-82da-4986-a81f-e794f59946c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8930a50a-d04a-40c9-a0b5-7b432275a00d</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-4</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8930a50a-d04a-40c9-a0b5-7b432275a00d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b63f62c3-4eac-40b0-a830-907c5257ffc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/500/Passbook Printing/TC_Passbook_Reprinting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>795c4c24-7e41-48a9-b349-59c72b446178</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Reprint Passbook</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>795c4c24-7e41-48a9-b349-59c72b446178</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Account_Number</value>
         <variableId>ec491d5f-f41f-41be-9211-925c6ca27df7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>795c4c24-7e41-48a9-b349-59c72b446178</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>START_DATE</value>
         <variableId>77b3afd1-e2e5-4c2e-ab85-34292edb2caf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>795c4c24-7e41-48a9-b349-59c72b446178</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>END_DATE</value>
         <variableId>d3d2e02c-27a8-4198-900c-afb3f443c7ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fa14ea0-bf95-4a98-bbd0-7393f9a2a3e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>12d8b786-9e51-4d15-b899-4c95e69aa5be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>51987935-5ddb-4210-8fbd-dfb23c195919</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>51987935-5ddb-4210-8fbd-dfb23c195919</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>51987935-5ddb-4210-8fbd-dfb23c195919</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>51987935-5ddb-4210-8fbd-dfb23c195919</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>018a018e-61f4-4651-90e9-265853f400cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f63e929-41bc-4be8-9620-f1dd79f2efd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e6752369-df13-458e-98a6-926fb6e2e628</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>5</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e6752369-df13-458e-98a6-926fb6e2e628</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83ead340-552e-4e3e-9a00-f63df30111b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/515/Reprint Passbook/Auth Passbook</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>02ca9ab8-4c6a-4aeb-b1eb-c1fe4f1746aa</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Reprint Passbook</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>02ca9ab8-4c6a-4aeb-b1eb-c1fe4f1746aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Account_Number</value>
         <variableId>ac604e29-14f3-442a-8307-f62c3abe3dae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcd87a8e-acde-46c7-9ce0-7cf5ae307364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b0d166-ce2f-40f2-97d4-ca3ca9c4e6ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27ce3870-8ee6-4d3a-8f8b-63edc051ef61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
