<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSCORE-00010 - Passbook Issuing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>392e85d4-b155-466a-bb94-95f65aba2ea4</testSuiteGuid>
   <testCaseLink>
      <guid>8398c7d1-d074-4891-993c-2ed4f1b8d720</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8359fe4d-c73d-4b63-b53d-4cd710465601</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8359fe4d-c73d-4b63-b53d-4cd710465601</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8359fe4d-c73d-4b63-b53d-4cd710465601</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8359fe4d-c73d-4b63-b53d-4cd710465601</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>760c0e32-96db-4f22-b489-8ef05d51ff63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3d2263d-ba46-43da-aecb-4c8cd2539595</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f48783ee-ff77-461a-a996-1d96430046c9</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-4</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f48783ee-ff77-461a-a996-1d96430046c9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eb8062a-4e35-47a5-8a46-b2c58c9042c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/500/Passbook Printing/TC_Passbook_Issuing</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a472533f-9ab1-47d2-bf9c-54c4cd5146e5</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>5,3</value>
         </iterationEntity>
         <testDataId>Data Files/Passbook Issuing</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a472533f-9ab1-47d2-bf9c-54c4cd5146e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ACCOUNT_NUMBER</value>
         <variableId>bbd5c0dc-21b9-45d7-aa91-ad308dc74891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a472533f-9ab1-47d2-bf9c-54c4cd5146e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PSBK_DEVICEID</value>
         <variableId>5f0daa9f-ed11-4372-a085-4f12345a8099</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c31ffa5f-23c7-48a5-ac66-5d06a49d7e8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
