<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSCORE-00063 - Input Lock_Hold amount ( RBU )</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e6093356-82a3-49e1-9ba5-3a67de5972e5</testSuiteGuid>
   <testCaseLink>
      <guid>2938c283-94c6-4922-8b34-4bece34cf72e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c92d147a-0141-4a4d-a726-f8375a0750bc</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c92d147a-0141-4a4d-a726-f8375a0750bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c92d147a-0141-4a4d-a726-f8375a0750bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c92d147a-0141-4a4d-a726-f8375a0750bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73d8c8d1-99df-4bc0-9543-979c256187fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0ddcc88-21b5-4036-9185-d575d57304b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>230080a5-03e6-467d-933e-0126ace45ff0</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>4</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>230080a5-03e6-467d-933e-0126ace45ff0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e224a58a-d37d-470d-bbfa-c0a2bca26ad9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>5ddc78ba-f639-42ac-8922-1a4392bb6d33</id>
         <masked>false</masked>
         <name>ACCOUNT_NUMBER</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/500/Input Lock_Hold Amount/Input Lock_Hold amount</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>265e9958-ef72-455d-b020-291b1755f6dc</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/Input Lock_Hold Amount ( TD )</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>265e9958-ef72-455d-b020-291b1755f6dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ACCOUNT_NUMBER </value>
         <variableId>5ddc78ba-f639-42ac-8922-1a4392bb6d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>265e9958-ef72-455d-b020-291b1755f6dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DESCRIPTION</value>
         <variableId>f120dc67-1ca0-4f63-9cf9-045ee6aeeb34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>265e9958-ef72-455d-b020-291b1755f6dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LOCKED_AMOUNT</value>
         <variableId>2afdfbf9-8379-4e5b-aa8f-16d02450ba0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c07e381b-bd0c-4f88-a3a8-7d2ea550be96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>424c1742-1eaf-4b15-99b9-3a0de8b93f3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0eb3846e-e25b-42fd-bc88-1ae0a5feea67</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0eb3846e-e25b-42fd-bc88-1ae0a5feea67</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>d36edea8-5e1a-4de3-82d0-0061d200d78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eb3846e-e25b-42fd-bc88-1ae0a5feea67</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b198ebb7-de9d-43db-9b7a-8f1ab9bfe05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eb3846e-e25b-42fd-bc88-1ae0a5feea67</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>T24URL</value>
         <variableId>da254404-607c-41bb-8786-4e3c2eda6ede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9fa3454-26e1-492c-84cc-d8f353c50df2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Choose_Branch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c16237-03c6-40fd-b000-aa277ec52348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dde1a45-3322-444d-a1ab-4704b49d86a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Input_Command_Value</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>49d5cac5-b859-4afc-bc33-5df27ff37632</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>5</value>
         </iterationEntity>
         <testDataId>Data Files/Input Command Value</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>49d5cac5-b859-4afc-bc33-5df27ff37632</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HMM</value>
         <variableId>788d54e2-7d72-4a2c-97d4-6c0ae54e85b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96b720aa-f8d7-42d4-9eaf-9eb9843425e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/515/Unauthorized Inputs/Unauth-Locked Funds</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>12398671-33b5-4278-86bc-ce71e4557cad</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/Input Lock_Hold Amount ( TD )</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>12398671-33b5-4278-86bc-ce71e4557cad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ACCOUNT_NUMBER </value>
         <variableId>01f1895e-b4c1-4be5-a77c-41e53f47579c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>12398671-33b5-4278-86bc-ce71e4557cad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LOCKED_AMOUNT</value>
         <variableId>b5e53443-25fe-45d2-8c6e-0fcd0a56655c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1144805c-5670-4b7b-b091-d62030f263d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8951e23b-1296-4ae9-bce5-30b890bd3ef0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Signoff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
