<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn - PERM.ADD - Yes</name>
   <tag></tag>
   <elementGuidId>7f3dca2c-48c8-42b7-b340-118878306b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='radio:tab2:L.PERM.ADD.CURR'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd813d3a-e892-4741-b448-ed465b11e058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_CUSTOMER radioCheckStyle_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>f5c2607e-3759-4b09-ae82-18d57cb34756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8daf19cf-a1a7-4ebe-9059-100b502d3c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab2</value>
      <webElementGuid>970893fc-0fe6-40e7-bbf1-9040b4eee47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>
          javascript:doFieldChangeEvent(event)
        </value>
      <webElementGuid>27812053-d3f6-4ec3-a16d-9547c065b348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>98238604-05b6-4038-9ba6-a54ca311f84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>f790ad65-efdb-43c4-9bcf-6ab096dde767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e6290d5-f769-4534-878a-287212a9749f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>24b05548-93bb-4509-a27e-edcc408cd1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab2:L.PERM.ADD.CURR</value>
      <webElementGuid>a6471f0d-a6f7-46d1-a2cc-a795bce40f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab2:L.PERM.ADD.CURR</value>
      <webElementGuid>a2a05107-a849-4906-a9ed-f9e98b06ebe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>8adf8f4e-3d17-406a-a382-cf0d7beabaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hot</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>1600cb06-195f-4d08-8a53-7794f333fb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>202371ed-2128-43ff-b412-4495420fc764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'');</value>
      <webElementGuid>89638e81-6f0e-4dc5-ae10-409ffef36296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('')</value>
      <webElementGuid>c9d2edda-5887-4c3d-b62a-21590f9fa133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab2&quot;)/tbody[1]/tr[9]/td[3]/table[1]/tbody[1]/tr[1]/td[3]/input[@id=&quot;radio:tab2:L.PERM.ADD.CURR&quot;]</value>
      <webElementGuid>a976758c-267b-4988-b4f1-caf9dbb4995e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[10]/td[3]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>331397e5-9140-40d8-9310-26647a434b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='radio:tab2:L.PERM.ADD.CURR'])[3]</value>
      <webElementGuid>89e8c99c-f55e-4b6c-bd42-7ea0fc0ba1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[3]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>9bdf1fd9-831f-461d-9c1a-9322db69434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'false' and @type = 'radio' and @id = 'radio:tab2:L.PERM.ADD.CURR' and @name = 'radio:tab2:L.PERM.ADD.CURR']</value>
      <webElementGuid>2e9d8fb6-afef-49f9-97a2-d86838b68800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
