<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>62562738-74a0-42d0-9bbb-9283bb75f522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab2']/tbody/tr[3]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>29f118a8-df05-4172-b042-543e32a34b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>60b31273-aeb7-4e32-8ed1-25df2ea4caab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mvdetails</name>
      <type>Main</type>
      <value>M_6.2_6.2</value>
      <webElementGuid>19430bc0-c9f3-436e-a42b-a05381baa1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svdetails</name>
      <type>Main</type>
      <value>S_6.1.2_6.1.2</value>
      <webElementGuid>933c7e84-d1ec-4f7f-a1f7-29331e917677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab2&quot;)/tbody[1]/tr[3]/td[3]</value>
      <webElementGuid>961e7328-9fff-4f9a-94a3-779fbfcd3265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[3]/td[3]</value>
      <webElementGuid>2d5882a1-c673-4cba-8759-dc66bc77fb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='House/Unit No/Bldg Name/Subd Name'])[3]/following::td[2]</value>
      <webElementGuid>c2a9bf0c-86f6-4f6e-a740-f801d574346b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit#, Floor, Building Name, Building/House#, Street, Subdivision, Barangay, Town/City'])[1]/following::td[3]</value>
      <webElementGuid>1caa9e3e-ef68-439b-b19f-6e3d832a5517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[2]/preceding::td[6]</value>
      <webElementGuid>c1aff093-a0d5-4643-af18-c46c273bc64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/preceding::td[10]</value>
      <webElementGuid>5b47d9b0-6006-4043-a992-8cca066ff79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[3]</value>
      <webElementGuid>0e02fd78-0aa6-43fd-a7b5-c88c45aa4fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
