<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Religion</name>
   <tag></tag>
   <elementGuidId>b5b80438-fbae-4b2d-a8ff-b4c065d8eb86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:L.RELIGION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdc2c1ab-f9e6-4b3a-9e27-6e0135c7595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e88561fa-d06b-4b8a-8186-37159a3947e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>4c426b07-cb59-434b-8914-f522f27155ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.MIDDLE.NAME</value>
      <webElementGuid>5bd6a365-457b-41f4-a2e9-3a8a896b1c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.MIDDLE.NAME</value>
      <webElementGuid>dffe423c-aa29-4b8b-847a-e9a6b78355e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>d6cc9cba-1547-4a6b-876a-447cf002d206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>eb3e8715-f8e3-4e02-a759-c20f12642f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>e86a87f3-ae6b-4c7b-a6a0-c1e0565cb8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cf41ce3-0d2c-47ae-a1be-978af7046114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>13d9313b-9e01-49cc-bb3d-9a47d3cb53af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>e5417352-eb8d-4fb5-90f0-8aa96539673c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.MIDDLE.NAME');</value>
      <webElementGuid>58ed0e4b-6beb-4111-bc69-0a3fc35c45bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event); doFieldChangeEvent(event);</value>
      <webElementGuid>fd576d77-635e-4320-b81e-ed36362ed87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.MIDDLE.NAME')</value>
      <webElementGuid>73e33094-0be1-4c3e-a9c0-872e77912cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.MIDDLE.NAME&quot;)</value>
      <webElementGuid>74130563-1c7d-4108-964b-d4b220c607a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>aac86397-b27e-4988-9157-8a3d0dafad2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:L.MIDDLE.NAME']</value>
      <webElementGuid>e971c739-a351-4260-9b9e-2ad3af31d7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/input</value>
      <webElementGuid>940f8dcf-ae17-4c20-994e-92ff010d0dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:L.MIDDLE.NAME' and @name = 'fieldName:L.MIDDLE.NAME' and @type = 'text']</value>
      <webElementGuid>b6237c2a-5f6e-4fa3-97c4-23427ae3719e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
