<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn - CUSTOMER.RISK - Normal Risk</name>
   <tag></tag>
   <elementGuidId>d0ec3894-ebe4-4993-953c-b5c555938c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='radio:tab1:CUSTOMER.RISK'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebddd068-2d09-4d05-a4de-e411e0f4170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_CUSTOMER radioCheckStyle_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>6d64c877-7ea3-468c-aabd-53b0f390b124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b8cfdc2b-5b46-4ef4-ad3d-a6c093606cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>d4a6da7e-cec2-4edf-a763-b566f46a1c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:toggleRadio(event)</value>
      <webElementGuid>82eb4f0e-593f-4d89-b279-a917c3a6037d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>1956995c-639a-411d-9acc-8ae0de0dafc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>260bfadd-934c-4742-b830-f16352c4c660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4cd2fb75-666b-4ed5-9ae8-837a37b00122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c8893668-aa25-4a7d-8404-4177aec2c876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>b02b1e01-87bf-44c6-b189-3165ed0952b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>ad27863d-7fc3-4f13-9b62-00ec1698d688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e3da4445-a730-43f9-a537-b1eb744a6d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
          javascript:clearEnrichment(event);
        </value>
      <webElementGuid>9a50c39f-dfd4-4051-ab0d-3de468285fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'');</value>
      <webElementGuid>5ea72597-7619-4252-87a2-447ac7634d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('')</value>
      <webElementGuid>73a6bf48-9966-47eb-af05-3728346146c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[32]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/input[@id=&quot;radio:tab1:CUSTOMER.RISK&quot;]</value>
      <webElementGuid>edb307ff-29d3-4f71-989e-68307aa93085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[33]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>91f83c08-2639-412f-af00-08d7af49ff31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='radio:tab1:CUSTOMER.RISK'])[2]</value>
      <webElementGuid>2456d504-3de0-415c-ba73-258368e773fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[33]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>af635dd4-e5a5-4b3d-a662-52934334c015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'false' and @type = 'radio' and @id = 'radio:tab1:CUSTOMER.RISK' and @name = 'radio:tab1:CUSTOMER.RISK']</value>
      <webElementGuid>9314e942-5270-4e92-9ac2-57dcbe03cf5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
