<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transaction_Completed</name>
   <tag></tag>
   <elementGuidId>33405f7d-6daa-4089-9b34-1bc5b7a5192f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I ' or . = 'Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2e7e18d2-3c89-4d56-8258-79f84a82962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>259e323b-d013-43bc-aa32-76d9c624174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I </value>
      <webElementGuid>c455da80-2d4f-4d05-923a-c8d0da56c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_CUSTOMER display_box_CUSTOMER_EWBS3INPUTV2&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>cf1c1008-f7b1-4348-9a05-95c92866b083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>ded218a4-c146-4884-b58a-3926ee4bc3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2004-LAS PINAS)'])[1]/following::td[7]</value>
      <webElementGuid>4942262d-21f6-45ad-88ea-4076490a3f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Details'])[1]/following::td[15]</value>
      <webElementGuid>d43c5d32-4f93-40f5-bde4-31dd3cdf419c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[2]</value>
      <webElementGuid>06f54c62-cb51-479e-8ce0-65aa6ebc2470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::td[2]</value>
      <webElementGuid>b7fdc18e-536f-4b68-b826-93deaefaa1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I']/parent::*</value>
      <webElementGuid>9c48ae18-c445-4fa3-af34-cca2576e2317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>80b4e715-972b-4316-9c00-0bbf17eace25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I ' or . = 'Txn Complete: 5177896 13:58:01 07 NOV 2022 CUSTOMER,EWBS3.INPUT.V2 I ')]</value>
      <webElementGuid>32f47234-8ac5-4dc6-8e61-c07141074ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
