<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New_Activity</name>
   <tag></tag>
   <elementGuidId>83b22a2f-3da8-43c0-a529-81cbbeec153c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'New Activity')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.enqDrillLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e7ad354-3310-4cb1-89c6-cdd0655f4aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqDrillLink</value>
      <webElementGuid>bf080253-10b2-473c-9c5f-d1632697530f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:drilldown('1','1_1')</value>
      <webElementGuid>804d5fa1-ffe9-4a3b-924f-2d4ad9111e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60a636ee-b60e-420c-b0a9-1bb019f52a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Activity</value>
      <webElementGuid>8c32559f-2021-4a4d-9fa9-7bab210cec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1_Heading100455919800&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_AAOVERVIEWHEADINGLIV&quot;]/a[@class=&quot;enqDrillLink&quot;]</value>
      <webElementGuid>f21d848a-976a-4806-9cdb-8d7d00e3537a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1_Heading100455919800']/td[2]/a</value>
      <webElementGuid>8edc46b8-ab5d-4aa1-bf5c-3947cef11b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Activity')]</value>
      <webElementGuid>4b888ed2-2fe2-4761-9a54-20cb8e470d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrangement Overview - Accounts'])[1]/following::a[1]</value>
      <webElementGuid>c644bc09-910f-42c6-9a04-2d50efe90772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrangement'])[1]/preceding::a[1]</value>
      <webElementGuid>770a72a3-f4e3-4c9b-864c-cd55a5678368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA211586HL4C'])[1]/preceding::a[1]</value>
      <webElementGuid>e68c12c7-7d47-4d79-afc7-f0201d339c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Activity']/parent::*</value>
      <webElementGuid>a2444094-da92-4dea-9f12-102323eb4298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:drilldown('1','1_1')&quot;)]</value>
      <webElementGuid>56da3199-d992-4e69-8712-bc60fec76b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>5bd01237-a879-453a-834f-44ac6ab6ebbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:drilldown(&quot; , &quot;'&quot; , &quot;1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1_1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'New Activity' or . = 'New Activity')]</value>
      <webElementGuid>1ff7b509-c92b-48c2-809a-928e1000563f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
