<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new password</name>
   <tag></tag>
   <elementGuidId>17a6e287-24d2-447e-b727-3d78a2b3cb1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#banner100064956801</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'banner100064956801' and @name = 'banner100064956801' and @src = '../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=BANNER&amp;skin=default&amp;compId=PH0010001&amp;usrRole=&amp;compScreen=COMPOSITE.SCREEN_EWB00975_100064956803&amp;contextRoot=&amp;windowName=banner100064956801&amp;user=EWB00975&amp;WS_replaceAll=&amp;WS_parentComposite=']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ba2aecdc-b011-45a0-a020-619bdacd6657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banner100064956801</value>
      <webElementGuid>aded63b4-790d-4a3c-98fe-6497527d37ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>banner100064956801</value>
      <webElementGuid>88b04cc7-91b3-4881-a6d8-a87805aca5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0482f9a2-d8c2-4e2c-ad01-ea0057279997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=BANNER&amp;skin=default&amp;compId=PH0010001&amp;usrRole=&amp;compScreen=COMPOSITE.SCREEN_EWB00975_100064956803&amp;contextRoot=&amp;windowName=banner100064956801&amp;user=EWB00975&amp;WS_replaceAll=&amp;WS_parentComposite=</value>
      <webElementGuid>aab0a5c9-d38f-4135-8f96-c1be9481ee0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner100064956801&quot;)</value>
      <webElementGuid>0ad0f466-7a8a-41ec-b1a7-5f0039c4836d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='banner100064956801']</value>
      <webElementGuid>ba129025-dd14-43c8-a2ff-a8779f4f2de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>4c44bedb-516d-4784-9a73-5adf0c845260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'banner100064956801' and @name = 'banner100064956801' and @src = '../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=BANNER&amp;skin=default&amp;compId=PH0010001&amp;usrRole=&amp;compScreen=COMPOSITE.SCREEN_EWB00975_100064956803&amp;contextRoot=&amp;windowName=banner100064956801&amp;user=EWB00975&amp;WS_replaceAll=&amp;WS_parentComposite=']</value>
      <webElementGuid>a9b70e72-fe8c-46b8-b4fd-72ff5ca14b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
