<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Relation</name>
   <tag></tag>
   <elementGuidId>b5adabc9-abf8-461d-bb68-53976016b06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='headtab']/tbody/tr/td[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c5398ac-7b4e-40cf-9157-e16f81908ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relation</value>
      <webElementGuid>913e5920-55f6-4958-b39e-141e7312879b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headtab&quot;)/tbody[1]/tr[1]/td[5]/a[@class=&quot;nonactive-tab&quot;]/span[1]</value>
      <webElementGuid>09cb975a-eaa3-4454-8cd7-fef49f0b701a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab']/tbody/tr/td[5]/a/span</value>
      <webElementGuid>1daeb41b-634c-47c1-b7c7-8b22d06ba4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Doc'])[1]/following::span[1]</value>
      <webElementGuid>e42ac742-62b6-48ff-b2ea-f62c3e0ee2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residential Details'])[1]/following::span[2]</value>
      <webElementGuid>59c00e29-2eb8-44b9-a6ea-ab44398bc723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Details'])[1]/preceding::span[1]</value>
      <webElementGuid>756c8a43-99e9-48c1-b185-95bcf89c5bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Details'])[1]/preceding::span[2]</value>
      <webElementGuid>bc079cc5-98c1-4f89-aa4e-64a099e4036d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Relation']/parent::*</value>
      <webElementGuid>941acb4c-e7dc-4e2a-902e-9c94fb1eaff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/span</value>
      <webElementGuid>21514ba2-809c-47fc-a3b0-4fa4d3ffae5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Relation' or . = 'Relation')]</value>
      <webElementGuid>3cdcfb6b-7658-4e3f-a527-c5b27e6eed14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
