<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5179390</name>
   <tag></tag>
   <elementGuidId>c3ee0cda-3d05-4505-8334-2cb9843872ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.iddisplay.iddisplay_CUSTOMER.iddisplay_CUSTOMER_EWBS3INPUT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toolBar']/table/thead/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>17fc1b48-5f27-4002-9ead-266f737a3cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25ea1257-62b0-4abb-801c-36abdde14d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iddisplay iddisplay_CUSTOMER iddisplay_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>d41ba18c-5f17-45f3-b2d8-048b22a4b8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5179390</value>
      <webElementGuid>27e9ab17-3c09-4529-ab92-1d59218f013b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolBar&quot;)/table[1]/thead[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[2]/span[@class=&quot;iddisplay iddisplay_CUSTOMER iddisplay_CUSTOMER_EWBS3INPUT&quot;]</value>
      <webElementGuid>da602fef-0c4c-4fdd-ab5a-faf976fe6a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolBar']/table/thead/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>307a634f-3663-43f0-8e23-eed5d72b92bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Details'])[1]/following::span[1]</value>
      <webElementGuid>c4d831f5-ff36-446d-88d5-4e652da51457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2004-LAS PINAS)'])[1]/preceding::span[1]</value>
      <webElementGuid>29464817-d21d-4420-bdaf-38f5f7f3339b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/preceding::span[1]</value>
      <webElementGuid>0adbf1e2-e9e2-4381-ad17-2a5a3c84c6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5179390']/parent::*</value>
      <webElementGuid>aab6969d-92c9-4c8b-a1ba-d23998046bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>419e4017-0fdc-4516-9b33-f2bade664a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5179390' or . = '5179390')]</value>
      <webElementGuid>d56a561b-206e-4bfb-97dc-d10a2229b388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
