<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KYC</name>
   <tag></tag>
   <elementGuidId>cba90c10-6bd9-4e57-89ae-a14f90c64382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='headtab']/tbody/tr/td[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>09aed93c-8a2a-49cf-ab93-3bd44bcaaab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KYC</value>
      <webElementGuid>7203ae73-7ee7-46c8-94e5-454c73a7cd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headtab&quot;)/tbody[1]/tr[1]/td[9]/a[@class=&quot;nonactive-tab&quot;]/span[1]</value>
      <webElementGuid>57b2366d-6c83-42fc-8120-bb9a0dbe9da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab']/tbody/tr/td[9]/a/span</value>
      <webElementGuid>3b1456e9-82e2-4771-97e9-01dd742ae03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Further Details'])[1]/following::span[1]</value>
      <webElementGuid>caf69d69-5bc0-4945-85f0-57e48aede51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Details'])[1]/following::span[2]</value>
      <webElementGuid>14daaac1-af29-4c7c-adac-f8c843ea7187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Details'])[1]/preceding::span[1]</value>
      <webElementGuid>71b57fb1-4af5-4b5b-9dd8-782cd669ad1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting Details'])[1]/preceding::span[2]</value>
      <webElementGuid>01150d28-c019-469f-ba83-e2696d9edbd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KYC']/parent::*</value>
      <webElementGuid>c0b93ad0-4645-472c-8a03-57f52ab54961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a/span</value>
      <webElementGuid>79d8953e-30f8-4dd2-9c9b-f3321a6a3d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KYC' or . = 'KYC')]</value>
      <webElementGuid>623eefe1-2a91-48c6-8f87-a2901f8da689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
