<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - IDs Presented</name>
   <tag></tag>
   <elementGuidId>68383598-6258-443b-a117-ff345ba4497c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:LEGAL.DOC.NAME:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf3b0bfb-4bc1-4895-b36a-6cc90e69b4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>49d9c718-0ed1-44af-ba17-49e497a17ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:LEGAL.DOC.NAME:1</value>
      <webElementGuid>da514075-76df-46d1-945d-63d25dacc5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:LEGAL.DOC.NAME:1</value>
      <webElementGuid>c08923d9-ada1-451c-9bc8-2ae9369ad2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3c1bafd-2a87-40c3-9fb3-6771142f94d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab3</value>
      <webElementGuid>0b871d68-771b-4659-a0f2-cacf1d3f849e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>ACR</value>
      <webElementGuid>e62fec7b-7a06-42e4-83e9-e89011e1bb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>69b60896-d420-4ebb-8669-ae67c6ff11ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>68a34e97-6458-4a9f-979f-e11a0a172544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_LEGAL.DOC.NAME:1</value>
      <webElementGuid>ad93952f-0080-479d-9c72-fdb57ba5fc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'LEGAL.DOC.NAME');</value>
      <webElementGuid>0b90f6e0-5117-45ba-acbc-91766022aba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('LEGAL.DOC.NAME')</value>
      <webElementGuid>c835865f-f7ad-4d34-b83a-b326400c8fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id</value>
      <webElementGuid>e1512233-ae72-40c4-a978-475dc7b80365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:LEGAL.DOC.NAME:1&quot;)</value>
      <webElementGuid>19ede63f-cabb-400f-9cdc-4f02fc808b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Communication Details Tab/frame_Capture object_VERAMEND015155711901</value>
      <webElementGuid>7703fc42-7905-429e-8c94-20d27466b89c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab3']/tbody/tr[4]/td[3]/select</value>
      <webElementGuid>f2ae4290-d997-485a-a858-4e1ea11bf0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:LEGAL.DOC.NAME:1']</value>
      <webElementGuid>bf660632-15c8-4d55-b586-0af40d6dda8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Presented.1'])[1]/following::select[1]</value>
      <webElementGuid>cc76f58a-c2ab-474e-9e5a-c6dde589a6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document No.1'])[1]/following::select[1]</value>
      <webElementGuid>792242fc-d3d2-413b-aef8-34060fc29565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Name.1'])[1]/preceding::select[1]</value>
      <webElementGuid>a810349c-127c-4913-bffb-1cd61c8986d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue Date.1'])[1]/preceding::select[1]</value>
      <webElementGuid>cf796135-b69c-48be-9c0a-d69bc4899f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/select</value>
      <webElementGuid>428816c3-9a2f-4a63-a9c2-c09ea75bfed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:LEGAL.DOC.NAME:1' and @id = 'fieldName:LEGAL.DOC.NAME:1' and (text() = '  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id' or . = '  AlienimmigrantcertofregistrationArticles Of AssociationDirectors Or Trustees ResolutionTaxform1903 RegforcorpandpartnrshpBir RegistrationBoard ResolutionCertofreg With BureauofcooperativesBarangay CertificationCompany IdAssoc Constitution And By LawsConsularized SpecialpowerofattorneyArticles Of Incorporation AndbylawsCredit CardCertofreg With DepoflaboremploymentDrivers LicenseDriving LicenseDepofsocialwelfaredevelopmentcertApplication For BusinessCert Of Business Name RegistrationGeninfosheetcertifiedbycorpsecrtaryGovtserviceandinsurancesystem EcardCertificate Of IncorporationMayors PermitNatlcouncil WelfareofdisabledpersonOfw IdValidids Issued By Othr GovtofficesOverseasworkerswelfareadminstrn IdArticles Of Partnership And By LawsPartnership ResolutionPassportPhilippine National IdPhilhealth CardPolice ClearancePostal IdPrcProposed Artcls Of Incorp AndbylawsScb IdSchool IdSeamans BookSec Certificate Of RegistrationSenior Citizen IdSocial Security NoSpecial Power Of AttorneyNotarizdspa DesignatedbyproprietorSocial Security System CardNotarized Tax Exemption AffidavitNotarized Treasurers AffidavitCert Of Tax Exemption Issued By RdoVoters Id')]</value>
      <webElementGuid>607f38ff-29a7-4ff0-8259-767c1e47dd5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
