<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tabs</name>
   <tag></tag>
   <elementGuidId>caf4be5e-5a61-4969-a973-0956e73aad0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${TAB}' or . = '${TAB}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nonactive-tab > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[text()=&quot;reason: ${REASON}&quot;]/../../tr/td[text()=${AMOUNT}]/../td[5]/a/img[@alt=&quot;Reverse&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>754718b2-a5e7-4938-8fbe-0c5ee45cf573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${TAB}</value>
      <webElementGuid>d8f2ad04-eae7-45ff-ab98-f17818b8e1be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab_main100614950602']/tbody/tr/td[2]/a/span</value>
      <webElementGuid>e07cde59-3950-4d76-808f-f0ae813f0cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorised'])[1]/following::span[1]</value>
      <webElementGuid>e09d404b-276d-4f3c-baaa-ae6b40bb3b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/preceding::span[1]</value>
      <webElementGuid>b5e167ca-11cd-4362-8028-528a3215405d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matured / Closed'])[1]/preceding::span[2]</value>
      <webElementGuid>2c3234c0-f07f-42f6-8dc6-17128f62b946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unauthorised']/parent::*</value>
      <webElementGuid>305ba4d5-3158-49ba-ad97-0dac4c92e947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/span</value>
      <webElementGuid>4cc54798-f3ff-415e-9587-f383ef8ab002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Unauthorised' or . = 'Unauthorised')]</value>
      <webElementGuid>61c89a02-42ba-459d-bbae-dfe0c40c5664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
