<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept Overrides</name>
   <tag></tag>
   <elementGuidId>78492c8a-4870-4e3c-a571-20bbd3ada416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errorImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error_box']/table/tbody/tr/td/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cd872bb-370b-4893-9f81-898d73aaae39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:commitOverrides()</value>
      <webElementGuid>97f5a2db-a0da-4f7f-8ea6-a82bd21a4ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e3a9473-c550-456e-be3d-3c0f672e7d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorImg</value>
      <webElementGuid>a19d58f4-4059-4898-b578-db6ca67acdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept Overrides</value>
      <webElementGuid>4ff54346-42e3-4665-9f13-499698611d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorImg&quot;)</value>
      <webElementGuid>679b1581-807f-4e5a-bc1d-d462e401b1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>27449648-1260-4141-bfc4-c7bdea2ca3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='errorImg']</value>
      <webElementGuid>fb4ba5d8-8b76-44ef-a775-bac12c857c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accept Overrides')]</value>
      <webElementGuid>18c547cf-a16f-4b5b-a0b1-3f441a141c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2719-AUTO SALES-SLBC)'])[1]/following::a[1]</value>
      <webElementGuid>06216488-c654-4936-acd4-753bb8307219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AAACT211583N5VHFHX'])[1]/following::a[1]</value>
      <webElementGuid>e58a2e77-35f2-4f53-97f1-de3856c5bd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settlement A/C 200043092412 does not belong to Arrangement Customer 5175058'])[1]/preceding::a[1]</value>
      <webElementGuid>e7765938-be2d-4734-a8c1-103bad356c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrangement'])[2]/preceding::a[1]</value>
      <webElementGuid>cfb2079c-2130-4b03-95bd-cd03a20cdad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept Overrides']/parent::*</value>
      <webElementGuid>b72185fd-c1c3-4e76-9157-83c7513bf9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:commitOverrides()')]</value>
      <webElementGuid>99caa0f6-80bf-4ded-b00c-6691fa1a3b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>2add54a0-9834-4bc0-ba0d-bb2bc1fc4b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:commitOverrides()' and @id = 'errorImg' and (text() = 'Accept Overrides' or . = 'Accept Overrides')]</value>
      <webElementGuid>26ce89ab-9934-4c6c-a52b-20161d239daa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
