<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Recurrance</name>
   <tag></tag>
   <elementGuidId>7301a11b-08b2-4dd0-b348-f298a8192056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Recurrance:M']/p[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b8129e8-4cc0-4f7e-a48a-9d6a3707b0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1bc0ffef-a954-4d70-bfaf-af0b47962905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Recurrance:M:On</value>
      <webElementGuid>0aec0320-bf79-42ec-997a-b983791e9324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Recurrance:M:On</value>
      <webElementGuid>223e7416-8b38-4678-832d-fa8b7ba2eed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>o</value>
      <webElementGuid>381403ef-ba15-4664-af49-7b4b75e28f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHideMonthDetail('');</value>
      <webElementGuid>ea9d36ce-107d-40ca-94e4-e8d306425541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>setFocusOnRecurrSaveOn(event,this)</value>
      <webElementGuid>95d3b63d-4f44-4a10-8fd3-cd2f5d3f7971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Recurrance:M:On&quot;)</value>
      <webElementGuid>c680e89d-3679-4435-b8bb-d6dfc80e6e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Recurrance:M']/p[2]/label/input</value>
      <webElementGuid>0e17eb4e-0948-4f40-865c-48fa19e3dc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Recurrance:M:On']</value>
      <webElementGuid>677a4646-e4f2-44e3-bd71-79c6c3039c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p[2]/label/input</value>
      <webElementGuid>54431cd4-fc12-4c20-88cb-9e3990cd4a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Recurrance:M:On' and @id = 'Recurrance:M:On']</value>
      <webElementGuid>f37cd602-6149-4be4-836c-901fb72b1585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
