<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Due Freq</name>
   <tag></tag>
   <elementGuidId>d593afca-0b9f-4596-bbd4-7a7a93f9a53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[4]/td[13]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ed99d73-8dea-4db1-9ef5-c560bb9fa88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>d45c16c0-375d-454f-bfca-2806094bbec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>da02b58a-f25c-41fd-bb78-1b5c65804ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>dropRecurrence(event);</value>
      <webElementGuid>506640f6-8731-481b-a13d-453c9807ade2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ade9a75b-0c5f-4433-aecf-223fdfe2a4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Recurrence Control</value>
      <webElementGuid>3ddd84ea-95de-4c38-a6c8-f2e2346c9aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_AAARRANGEMENTACTIVITY dropdown_button_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>5a4ea1f4-e755-47b1-bed3-719b5f997656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/deal/recurr.gif</value>
      <webElementGuid>0bc91f7e-5f23-460b-8731-8bbd03ef9322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>recurrencedropfieldname</name>
      <type>Main</type>
      <value>fieldName:DUE.FREQ:1:1</value>
      <webElementGuid>d20551ab-7cdf-4608-8efd-384ff0b3e7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AA.ARR.PAYMENT.SCHEDULE,AAAA211589YQYN-SCHEDULE-20210607.1&quot;)/div[@id=&quot;contract_screen_div&quot;]/table[@id=&quot;alltab&quot;]/tbody[1]/tr[2]/td[1]/table[@id=&quot;tab1&quot;]/tbody[1]/tr[4]/td[13]/a[1]/img[@class=&quot;dropdown_button dropdown_button_AAARRANGEMENTACTIVITY dropdown_button_AAARRANGEMENTACTIVITY_AANEW&quot;]</value>
      <webElementGuid>01d4a4bd-7752-49ba-b527-16d613f6a834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[4]/td[13]/a/img</value>
      <webElementGuid>c4f356ea-404d-40d9-ac33-022b2218d419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Recurrence Control'])[4]</value>
      <webElementGuid>3ecf2a23-f1c5-4c39-bf0b-8970d817daa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/a/img</value>
      <webElementGuid>065d3b06-cf76-4b35-bf5f-02e96f272649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Recurrence Control' and @src = '../plaf/images/default/deal/recurr.gif']</value>
      <webElementGuid>bdc91713-f568-43c9-a3c3-50adeae6b9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
