<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Method Pymnt Freq Check</name>
   <tag></tag>
   <elementGuidId>14095485-68ae-4359-9e82-ee0855356496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toolbar_icons']/table/tbody/tr/td[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8dd8f61a-220d-4bc2-a4f9-d4cc0d9f59c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ascell</value>
      <webElementGuid>59a41e5d-62f6-4d26-8a88-b14d0ccdc4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>7a85efa7-c5ac-406b-ad9a-0d3431475f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>09157719-ede1-4204-be64-9498d73415e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>rec_saveDateonKey('fieldName:PAYMENT.FREQ:1',event);</value>
      <webElementGuid>66d05f54-06a4-49c2-97f8-b4b4e1e42cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8fab7084-e0c6-4c9d-9c60-0e502ba9cf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/deal/save.gif</value>
      <webElementGuid>27fe0733-3744-4a96-95a8-e0532a20d9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ab8140ed-9be7-4b6a-8c13-decc82a04013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>17d7859e-7657-4ca6-981c-cf9c405a0e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolbar_icons&quot;)/table[1]/tbody[1]/tr[1]/td[2]/a[1]/img[@class=&quot;ascell&quot;]</value>
      <webElementGuid>19b336a9-f982-44df-ae00-b56357edb7b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbar_icons']/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>c7479e14-5219-4e3e-9e5e-ac558ac02abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Save']</value>
      <webElementGuid>45cbda32-fde4-4296-b526-27eb3d3605ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>9e2e0251-7fd2-4422-920f-ae07494050f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/deal/save.gif' and @alt = 'Save' and @title = 'Save']</value>
      <webElementGuid>7cc3607e-6a1e-4268-a11f-db78291e932b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
