<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Method Pymnt Freq</name>
   <tag></tag>
   <elementGuidId>dae85d03-a91c-4c3e-8c30-a03da886fd77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[4]/td[7]/a/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2cdb94d1-877e-4422-bde2-bb621bf3163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>9e329286-ef21-48e4-9d80-c957f53e9068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>eb08d797-6c1f-46b7-9494-11992d8d403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>dropRecurrence(event);</value>
      <webElementGuid>cf3a76c0-b1ed-440b-b3f5-36e9f9615bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6078bcf2-0bf3-4473-bc10-c13e75b733c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Recurrence Control</value>
      <webElementGuid>a1be26d1-4089-4a23-9648-56da983fdd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_AAARRANGEMENTACTIVITY dropdown_button_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>3f47e9c2-09f5-4259-aa9d-51cc64c7d9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/deal/recurr.gif</value>
      <webElementGuid>31874171-95eb-4d8c-9319-890d2268489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>recurrencedropfieldname</name>
      <type>Main</type>
      <value>fieldName:PAYMENT.FREQ:1</value>
      <webElementGuid>44367252-72bc-42e0-b2bf-06a9c5ce373f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AA.ARR.PAYMENT.SCHEDULE,AAAA211589YQYN-SCHEDULE-20210607.1&quot;)/div[@id=&quot;contract_screen_div&quot;]/table[@id=&quot;alltab&quot;]/tbody[1]/tr[2]/td[1]/table[@id=&quot;tab1&quot;]/tbody[1]/tr[4]/td[7]/a[1]/img[@class=&quot;dropdown_button dropdown_button_AAARRANGEMENTACTIVITY dropdown_button_AAARRANGEMENTACTIVITY_AANEW&quot;]</value>
      <webElementGuid>6fc38f54-b8fe-4f12-a408-82896236a070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[4]/td[7]/a/img</value>
      <webElementGuid>7a74c2d7-163f-4ac5-8313-fa66563e284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Recurrence Control'])[3]</value>
      <webElementGuid>5dd6e4ef-b389-49f6-be51-9719d87dac04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/a/img</value>
      <webElementGuid>ad586128-a12d-4e78-ba9a-fec27d3820b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Recurrence Control' and @src = '../plaf/images/default/deal/recurr.gif']</value>
      <webElementGuid>26c881f5-a673-42e2-9e79-a850750429bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
