<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Txn Complete</name>
   <tag></tag>
   <elementGuidId>fea7165e-1f8a-4e00-ada0-8bc819c02bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ce24d759-df00-4dce-877d-d3f97e6fff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>1b7ae1aa-a3d8-41f5-874a-5fe1bbfae9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Complete: 200058048681 13:29:17 01 SEP 2023 ACCOUNT.STATEMENT,EWBS3.PASSBK I </value>
      <webElementGuid>fefd53c2-6c21-4b17-8eef-ac9a99b241b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_ACCOUNTSTATEMENT display_box_ACCOUNTSTATEMENT_EWBS3PASSBK&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>46be7c7a-520b-4d20-ad66-8ddad27691b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>765e3960-526a-40dc-850c-e40e0c17afa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2004-LAS PINAS)'])[1]/following::td[7]</value>
      <webElementGuid>0abf0a53-ed81-43a8-b4ec-3481592adabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passbook issue'])[1]/following::td[14]</value>
      <webElementGuid>b124bb88-f34a-43cc-8212-1dc682632c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[2]</value>
      <webElementGuid>a1aeb400-d9a4-41ed-b35b-42f573510e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::td[2]</value>
      <webElementGuid>8540a490-c210-40f0-b62b-70227ab2bcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Complete: 200058048681 13:29:17 01 SEP 2023 ACCOUNT.STATEMENT,EWBS3.PASSBK I']/parent::*</value>
      <webElementGuid>b07e47be-27ff-4a85-8800-de0f634acf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>26c4bbde-536b-4dee-b54f-aa903c1db4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Complete: 200058048681 13:29:17 01 SEP 2023 ACCOUNT.STATEMENT,EWBS3.PASSBK I ' or . = 'Txn Complete: 200058048681 13:29:17 01 SEP 2023 ACCOUNT.STATEMENT,EWBS3.PASSBK I ')]</value>
      <webElementGuid>db0b2b6e-df9b-4e7d-a317-b6e69815bfb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
