<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Reverse a deal</name>
   <tag></tag>
   <elementGuidId>5db35749-c499-4b5a-b2c3-e18f40005fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Reverses a deal from the live file']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73cc9067-29f6-4e42-8208-3a9fcb12f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad93defc-4524-42f7-830b-90e638dd2cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>5f854413-d4cf-40ee-944d-d34fe7ead08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:DESCRIPTION</value>
      <webElementGuid>aff61346-45b1-4c0a-a9bc-4d907938bf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:DESCRIPTION</value>
      <webElementGuid>28089f8d-f51a-4807-ad76-0a3497484bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>008f2a0d-3c2f-4560-84c1-2d04418a1860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_ACLOCKEDEVENTS dealbox_ACLOCKEDEVENTS_INPUTSCV</value>
      <webElementGuid>b06ba64c-d9c2-403c-affd-25aa53fbc562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>00c1e36c-8bb4-4e30-91cc-16bd69ea1607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b5f21d7-c89e-4afe-a34b-bb1668740276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>8e168f75-adbf-4c9a-9044-6a7398dcf2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>914cb78d-151f-4b63-9b16-23ea9cf554ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_DESCRIPTION</value>
      <webElementGuid>a0766c23-48ba-4980-a2c5-e250381408bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'DESCRIPTION');</value>
      <webElementGuid>1217889b-2e69-4a5f-b985-bba80250da33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('DESCRIPTION')</value>
      <webElementGuid>2e1ac158-021e-4acf-a910-a7168ec03173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:DESCRIPTION&quot;)</value>
      <webElementGuid>ae35004e-460a-4ede-94ff-9ef80a45339c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
