<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clkCompanies</name>
   <tag></tag>
   <elementGuidId>f174ecc9-df9f-4439-af15-a1142c7c87fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane_']/ul[2]/li/span[(text() = 'My Companies' or . = 'My Companies')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'My Companies' or . = 'My Companies')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b4d7c48-16f6-4e1c-a2cc-f041b5e8d6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>d4019bd0-a470-4bc2-8ac6-39b67b7d92ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>fcc6751e-3c0b-481b-8cd7-8ee5a4380205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Companies</value>
      <webElementGuid>2e3da39e-0c1f-42dd-818e-9747471b5fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>d84e83c8-ef75-4d52-b5d6-c806b014f5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[2]/li/span</value>
      <webElementGuid>43ea8549-d77a-41d8-85bd-569aea05c976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[2]</value>
      <webElementGuid>168f83f4-5104-4856-a0e8-2ea2d6737242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate Profile'])[1]/following::span[1]</value>
      <webElementGuid>657a3b9d-78ba-4189-953d-b0f618264146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organise favourites'])[1]/following::span[1]</value>
      <webElementGuid>a88569b8-7ffa-47da-90f8-496bf6121888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('2015-PRESIDENT', &quot;'&quot;, 'S AVE.')])[1]/preceding::span[1]</value>
      <webElementGuid>d9c53191-f1ce-4c07-8429-3dcc22fe78c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T24 NEW UAT'])[1]/preceding::span[1]</value>
      <webElementGuid>48ffb4fe-bd8c-45ec-b368-90e2dc6bf227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Companies']/parent::*</value>
      <webElementGuid>e442bd91-c874-401e-a373-e5613d4fcf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/span</value>
      <webElementGuid>8072ae02-02d9-4e0a-934b-253f029d9335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My Companies' or . = 'My Companies')]</value>
      <webElementGuid>e6490243-9b47-463b-a904-be7c50a7f458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
