<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_authorise</name>
   <tag></tag>
   <elementGuidId>856dbaed-cd18-4097-9f61-3d0da7d25968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Authorise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0529b7c5-1c1a-4d57-a5c7-c5038ba13e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668126730622</value>
      <webElementGuid>25c74f74-0383-48d8-bb25-a6a4ffe4574d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
