<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Source of funds</name>
   <tag></tag>
   <elementGuidId>d17c5fa1-ea78-45a1-a834-d867ff2003d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a7c86d6-1d78-4ccb-8eba-137695864347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>e833d098-66aa-4fdc-94d9-afe6ad2d40c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>e14a482d-fc9f-48e2-9f7d-6be9b9ba3438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>6e30ccdb-967e-4d48-895e-3f72847509f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>924f76fe-b0b2-48c9-85f9-206b5697fcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab5</value>
      <webElementGuid>84ba11b2-82ec-4145-84a9-78a49a4e3937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>fe55393a-eccc-4366-9f98-0008774e5eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>ce8d654a-1519-46f8-b486-4b3663f86424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SOURCE.OF.FUNDS:1</value>
      <webElementGuid>b361dcb5-f340-4036-841c-bfd9a2deeb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SOURCE.OF.FUNDS');</value>
      <webElementGuid>a162218a-8c9c-4012-b6f4-653bec7f4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SOURCE.OF.FUNDS')</value>
      <webElementGuid>46b68ffb-a290-42ab-8a13-551502287f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus</value>
      <webElementGuid>d986f4c1-59d7-430e-b24e-2227d1984c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SOURCE.OF.FUNDS:1&quot;)</value>
      <webElementGuid>913cefc7-84e2-4e18-8a1c-c359c9737f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab5']/tbody/tr/td[3]/select</value>
      <webElementGuid>09f03839-e742-459a-afa6-e5b16aa451e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      <webElementGuid>4bc3ada1-62b6-475e-b6b2-22d6b4e18ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[2]/following::select[1]</value>
      <webElementGuid>b8baa689-9721-43fa-b041-0d0fae557a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Liability'])[1]/following::select[1]</value>
      <webElementGuid>f5bbd605-932e-40e5-8864-4f2f12e81297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Size'])[1]/preceding::select[1]</value>
      <webElementGuid>f15196e9-2866-409f-87eb-7da1b84955b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Bank Accounts.1'])[1]/preceding::select[2]</value>
      <webElementGuid>3f8bf83b-c0ff-4d22-b55a-86efe783d7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[3]/select</value>
      <webElementGuid>3aaefd0a-81fd-4a7b-824c-0860765160a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:SOURCE.OF.FUNDS:1' and @id = 'fieldName:SOURCE.OF.FUNDS:1' and (text() = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus' or . = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus')]</value>
      <webElementGuid>419de13c-7504-414f-8e26-6d0ab86c39f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
