<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectRole</name>
   <tag></tag>
   <elementGuidId>11298be3-1025-42d2-90fc-bf11022cce17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[6]/td[3]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9cc5f0d2-cbd5-46ee-b5dc-96848edf20fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_AAARRANGEMENTACTIVITY dealbox_AAARRANGEMENTACTIVITY_AADRILLPC</value>
      <webElementGuid>3e150ef0-6c64-4fe3-8fd3-a28e9fbe82b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:ROLE:1</value>
      <webElementGuid>54276197-1766-48ac-9b6f-b58925df7182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:ROLE:1</value>
      <webElementGuid>616bd3fe-246a-4957-aba1-5fadb369c11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>83b6c3e1-6e1d-4114-84e8-f290906e91b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>f515685a-5284-4bd0-aea6-0c0fffceba61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>41f09a9e-ad5b-49ba-a2f0-19ed6055bbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_ROLE:1</value>
      <webElementGuid>05ebc21f-1d13-4dfd-8165-806e8aaa2e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'ROLE');</value>
      <webElementGuid>c51f198e-4cef-44d7-8a24-60b1fdcbe745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('ROLE')</value>
      <webElementGuid>ea682f99-c6ee-4d67-a72b-1c96562a3633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  BeneficiaryCo-brrowerCo SignerDep.assigneeGuarantorGuardianAdministratorItf/faoJoint Owner (And)Joint Owner (Or)Joint &amp; Several SigAtty In FactSuretyUnregistered Company (Titf)Trustee</value>
      <webElementGuid>122c80d2-5190-47c9-b08f-367efc275a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:ROLE:1&quot;)</value>
      <webElementGuid>8b870e2d-829d-42f8-a246-ac90478953ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[6]/td[3]/select</value>
      <webElementGuid>b1c8ea6f-cbf0-4e8f-8372-38eebcbf37a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:ROLE:1']</value>
      <webElementGuid>217745c4-112a-452b-9730-cc77cdb68510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role.1'])[1]/following::select[1]</value>
      <webElementGuid>e5e1b685-710d-4794-a9c9-d7638421c4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Party.1'])[1]/following::select[1]</value>
      <webElementGuid>5a53aa27-d89d-46f6-a58b-61fcd750d18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes.1'])[1]/preceding::select[1]</value>
      <webElementGuid>96517901-b91a-4f99-9cdc-c37b75427f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EWOP Tagging'])[1]/preceding::select[1]</value>
      <webElementGuid>7f18be9a-5a7d-4d5c-b953-b77bad76c733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>be8c2258-e2d2-4cf8-8623-ab4a32e94af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:ROLE:1' and @id = 'fieldName:ROLE:1' and (text() = '  BeneficiaryCo-brrowerCo SignerDep.assigneeGuarantorGuardianAdministratorItf/faoJoint Owner (And)Joint Owner (Or)Joint &amp; Several SigAtty In FactSuretyUnregistered Company (Titf)Trustee' or . = '  BeneficiaryCo-brrowerCo SignerDep.assigneeGuarantorGuardianAdministratorItf/faoJoint Owner (And)Joint Owner (Or)Joint &amp; Several SigAtty In FactSuretyUnregistered Company (Titf)Trustee')]</value>
      <webElementGuid>74b000fb-2e76-4d60-a83c-7faf56490cad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
