<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputArrangementID</name>
   <tag></tag>
   <elementGuidId>f87cbd59-ed06-4ec1-a86c-c9f51e3753ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = '{ArrangementIDValue}' and @id = '{ArrangementIDValue}']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr/td/input[contains@id=&quot;${ArrangementIDValue}&quot;]
//input[@id='value:1:1:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12697cda-b942-403f-89f9-b05630b6d5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21ec5c8a-50e8-4306-bb6f-961fd98580aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>{ArrangementIDValue}</value>
      <webElementGuid>ff1ac9d0-cb33-4e53-96fd-e4281fca0327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>{ArrangementIDValue}</value>
      <webElementGuid>311a5d2d-989a-4e80-b394-c7366c5e4cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>614c017f-d8a5-4648-96ff-738510617dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>{ArrangementIDValue}</value>
      <webElementGuid>cb76b8ac-bf3b-4456-b28a-28cc8735a2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_AAFINDARRANGEMENTNAUAR</value>
      <webElementGuid>6c520a54-4a1e-4438-9a66-839e4cedd43d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay_workarea100405813003']/tbody/tr/td[3]/input</value>
      <webElementGuid>2e5eec93-1caf-4417-ae8d-37031d3177ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id={ArrangementIDValue}]</value>
      <webElementGuid>042154bd-8f97-4e3a-9077-deabfa3c8c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>97d14a89-6fe4-488c-a639-cb27f3d2faa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = {ArrangementIDValue} and @id = 'value:1:1:1']</value>
      <webElementGuid>746aff75-c145-402a-a58a-abdfbc9506ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
