<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelOwner</name>
   <tag></tag>
   <elementGuidId>c736667e-abe6-4d8e-b436-27680a0f04af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Owner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f62f059e-ad05-42ef-b3b7-7dc65c931403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668501311818</value>
      <webElementGuid>63aa9ee9-1da3-49b8-9f84-b37965b448a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
