<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCurrency</name>
   <tag></tag>
   <elementGuidId>b8eddea2-bd51-42bb-bd41-e28e09c71c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Currency')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>43a69418-ca2d-4a84-b632-86abbfc9b60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668501648146</value>
      <webElementGuid>0a999ddb-c552-4df0-98cd-a57149a2ea5e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
