<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelArrangement</name>
   <tag></tag>
   <elementGuidId>958906ed-14ee-4d2b-8aeb-42ec2627914f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Arrangement')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>030bd448-98c2-4b4d-b0c2-f9c4f02e7f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668501254904</value>
      <webElementGuid>412a3e5d-b175-41f6-9adf-ae9ac599e89e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
