<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelProductGroup</name>
   <tag></tag>
   <elementGuidId>0441021e-495f-48bd-bdd6-8a69da84eae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Product Group')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c3eace31-665b-4c48-8497-6a397101a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668501337730</value>
      <webElementGuid>0c7cc144-a091-4701-8dfe-bcffa1609ebb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
