<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Amend</name>
   <tag></tag>
   <elementGuidId>49031b6e-faf1-4f42-b56d-739584c7b715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Amend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Amend&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d4089ac-cf3f-43af-932b-cad364066900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/enquiry/drilldown/edit.gif</value>
      <webElementGuid>16b8392d-cb99-44d6-a78b-32f111cbec28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amend</value>
      <webElementGuid>fbbd0b7a-7ea9-4c50-90de-b2660b4895aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Amend</value>
      <webElementGuid>4895703c-1591-42e4-9990-158ea32fc864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_EWBS3CUSTAMEND&quot;]/a[1]/img[1]</value>
      <webElementGuid>f4ca1e74-e743-46c0-8fd8-44e6ff98116c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer IND/Amend Customer/frame_Capture object_ENQAMEND100344753900</value>
      <webElementGuid>2e83d47e-d57a-4a19-9d0d-be91854b8982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[5]/a/img</value>
      <webElementGuid>ec259731-04db-4f25-aeb6-cf6d69d8e5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amend']</value>
      <webElementGuid>590d8062-902c-4043-9909-83a24c9b64b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/img</value>
      <webElementGuid>5a640a5e-3a84-4119-96e0-c0927069ada2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/enquiry/drilldown/edit.gif' and @alt = 'Amend' and @title = 'Amend']</value>
      <webElementGuid>3da96093-f4db-40af-8569-1eeb260d5f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
