<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_VERAMEND100344753901</name>
   <tag></tag>
   <elementGuidId>127fdf0e-b8bb-46de-9e58-7168325744c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VERAMEND100344753901</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ede23cc0-f154-439a-9098-335ce739894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VERAMEND100344753901</value>
      <webElementGuid>9d1cdab2-e7cc-4bc6-99bb-3105fef8d26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VERAMEND100344753901</value>
      <webElementGuid>dd99da0e-120c-4662-91ba-46922acbef26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>118482fc-517a-4a17-9291-25b10a9fd624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>d9d13dcb-5d6b-4436-a627-d6f829fc5ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VERAMEND100344753901&quot;)</value>
      <webElementGuid>d412175c-69c3-414d-ad9a-b62ebe6b11dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='VERAMEND100344753901']</value>
      <webElementGuid>1cd5213e-12b2-49d6-b9e1-ac93c2e18eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>2aadcc5e-c06d-4da2-b948-69c6699d50f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'VERAMEND100344753901' and @name = 'VERAMEND100344753901' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>3669b924-4bae-4ff6-93ab-129898aff890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
