<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PERM.PROVINCE</name>
   <tag></tag>
   <elementGuidId>00f1193e-db3a-41ca-b4eb-f4bc14e8b7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:PERM.PROVINCE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42209a63-b187-4cef-bb23-877110347271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0abb490-863c-4d88-958e-47833bc93138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>18446fe1-3210-4642-8641-5c12e39d88e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:PERM.PROVINCE</value>
      <webElementGuid>b18903ca-27dc-4f69-bbeb-30b8f3cf9363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:PERM.PROVINCE</value>
      <webElementGuid>da3cc488-9ce8-47ff-ad45-87cf1ca30784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab2</value>
      <webElementGuid>a047d652-5657-424e-87ee-cd8e335be34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QUEZON CITY</value>
      <webElementGuid>7f8b2ec3-07ac-4584-86bd-c51502a41e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>QUEZON CITY</value>
      <webElementGuid>7f7d6bde-f022-4879-8590-0b4f43e4fdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>b0185890-1e31-43d4-a829-efc03ef5ef00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>186e392e-e678-4f35-bb36-6d704b4c7881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dcda16df-762b-4f95-91f8-624fba2be902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdown</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>c9596a94-268f-4b83-b150-0ebda61c3e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>8bdc4b71-9937-4c66-a42b-c2a67380d318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event); doFieldChangeEvent(event);</value>
      <webElementGuid>555df99d-6074-4cd3-9f33-00191ea2aa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>97c48a23-8f57-4405-9d24-9645d5cd9d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>a9040f78-3c04-4335-918e-74cf856dc488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'PERM.PROVINCE');</value>
      <webElementGuid>8bb3dcf5-7e63-4e9e-85d4-a80059db138a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('PERM.PROVINCE')</value>
      <webElementGuid>78e83582-6e10-4914-af80-362669a33860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:PERM.PROVINCE&quot;)</value>
      <webElementGuid>feb51888-d9ea-43c1-89a0-c86979452f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Customer Tab/frame_Capture object_VERAMEND100453869301</value>
      <webElementGuid>857769dd-37c1-4576-ae02-eedb9fa26353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[10]/td[3]/input</value>
      <webElementGuid>85e09857-a0bb-4d72-884e-395f34afe5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:PERM.PROVINCE']</value>
      <webElementGuid>aabd1fe0-9edb-4402-9f33-88aafe3c99b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[10]/td[3]/input</value>
      <webElementGuid>949a4f09-8fb5-4dc9-b3e5-3da7b81f9f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:PERM.PROVINCE' and @name = 'fieldName:PERM.PROVINCE' and @type = 'text']</value>
      <webElementGuid>c680f8ab-19df-47fc-afc1-6761f599d6c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
