<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Teller Menu</name>
   <tag></tag>
   <elementGuidId>a8750b95-fd44-47f9-bb36-d7686452c2ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane_']/ul/li/ul/li/span[text()=&quot;${TellerMenu}&quot;]/img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[text() = &quot;${TellerMenu}&quot;]/img[@id=&quot;imgError&quot;][count(. | //*[@tabindex = '0']) = count(//*[@tabindex = '0'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97e8d6dc-3d4f-465e-8657-b95c3256174a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66da6af5-81ac-4ba5-abe5-a39586f60e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgError</value>
      <webElementGuid>b9fcaeaa-5c08-4105-9813-4f6c6ae30cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/menu/menu_down.gif</value>
      <webElementGuid>921a9590-bcd2-4187-a1d2-d0fab76cb793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[text() = &quot;${TellerMenu}&quot;]/img[@id=&quot;imgError&quot;]</value>
      <webElementGuid>3ed863e4-b283-4c7b-9a9f-b41b1aa317fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[2]/li/ul/li/span/img</value>
      <webElementGuid>a04b941e-8619-4582-93a5-1a2c7a90151f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='imgError'])[5]</value>
      <webElementGuid>0e804a94-10ab-4c90-9d4b-d0e8be3a56ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/img</value>
      <webElementGuid>586a2ce1-4c53-44b4-bee4-60f4ab7f14e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgError' and @src = '../plaf/images/default/menu/menu_down.gif']</value>
      <webElementGuid>e7642c6b-663d-4bd0-bc42-f544c804aebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
