<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_VERAMEND100455231201</name>
   <tag></tag>
   <elementGuidId>34c74f9d-6e65-479f-9d92-fec2fdc9fb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VERAMEND100455231201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>b2790163-c2b0-4df7-8638-8bc7fab4e63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VERAMEND100455231201</value>
      <webElementGuid>28d1f4b7-59b4-4496-b359-8ce860ef5e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VERAMEND100455231201</value>
      <webElementGuid>d71ac29c-2a27-4e70-b05c-aa6655faa152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4a6d70c6-bc73-4416-9336-d8ae091979e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>55ded8b2-0f6e-4a52-9eb8-58a4786a744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VERAMEND100455231201&quot;)</value>
      <webElementGuid>3c62d583-a523-42b8-b030-fcf7fa3cd060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='VERAMEND100455231201']</value>
      <webElementGuid>1940e49e-e5f4-4ea1-b1c2-76da9c5710bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>803e70fb-bcda-4668-858f-b093729e583d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'VERAMEND100455231201' and @name = 'VERAMEND100455231201' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>9d09950c-c016-48d5-88ff-5987e7079abe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
