<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Introduced By</name>
   <tag></tag>
   <elementGuidId>77472cf2-34c6-4438-a532-11c56e655beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:INTRODUCER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe3cff54-29a4-4fbc-8d5f-2184b450c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f43db479-9701-4f25-81f2-b3c2248df3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>95640b5b-c52b-4ff8-afa5-9418ab6260b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:INTRODUCER</value>
      <webElementGuid>a31d9d7d-4e70-4aa4-a216-e3931017fca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:INTRODUCER</value>
      <webElementGuid>f69e1863-26ed-4b25-99ad-497414ba2166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab6</value>
      <webElementGuid>292f8219-cb97-4c74-8f3a-787d50a0e992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ITG00918M</value>
      <webElementGuid>2ec4faec-eebc-4b64-b4b3-17ed24116b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>ITG00918M</value>
      <webElementGuid>1b846519-82e6-4bc0-90dc-ef79d5fd31a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>df92ad59-0a73-4ea5-b52e-644ad6ccc6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>1f0b7ac5-0a7c-458d-8f6a-e57e1ad48959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1662c1c6-a189-43e8-8e7e-c0b72c9d6e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>ab8890a1-dd98-4209-a28e-b351e422d179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>5da10ca1-e3e6-464c-bdc8-c69c1b4fceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_INTRODUCER</value>
      <webElementGuid>e536afe9-277b-4730-8852-08c989aa7123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'INTRODUCER');</value>
      <webElementGuid>ca3493c9-026c-4d80-a8cf-57b7904438a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('INTRODUCER')</value>
      <webElementGuid>56141fad-a4a3-436e-b1e9-ba0ab4d59b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:INTRODUCER&quot;)</value>
      <webElementGuid>d513f308-199d-42be-bac4-78016296eb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Communication Details Tab/frame_Capture object_VERAMEND015155711901</value>
      <webElementGuid>f08813d4-c476-4fc2-9aea-d68b77dff121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab6']/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>009de0dc-462a-45b5-8da2-c5d8d3dbffb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:INTRODUCER']</value>
      <webElementGuid>27a351e8-8c0c-444e-9f38-808b5fb3357f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>95ad42e7-7d5d-4e49-8ada-391cb31377ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:INTRODUCER' and @name = 'fieldName:INTRODUCER' and @type = 'text']</value>
      <webElementGuid>bfd995da-c8fc-4616-a5ea-7fef3e6e6daa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
