<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAccountNo</name>
   <tag></tag>
   <elementGuidId>50c065b4-7cf1-4bb0-b6e5-fe21f853163c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:ACCOUNT.2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a9c7745-702a-4fc6-a516-5a1d1b2a2022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20eb74d0-e6db-45ec-9902-2aac786fe6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>59428b4a-fda5-43ce-a998-8d73da2668e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:ACCOUNT.2</value>
      <webElementGuid>c17dac00-5686-43bf-8bce-80d03bd0d51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:ACCOUNT.2</value>
      <webElementGuid>944360c7-3af1-4653-a943-edc67e7cb367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>b3d7e08b-401b-4636-b1db-cbaa1b77971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TELLER dealbox_TELLER_EWBS3LCYCASHDEPOSIT</value>
      <webElementGuid>91d28017-82aa-41d3-99f1-d1094bdc93c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>e0d25a13-5e65-4455-aeec-587fc56bf26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0c8e06f-c4f0-46d9-ba83-d7cfdd853b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>6bbae997-7a62-4a15-b111-ee66b59cc47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_ACCOUNT.2</value>
      <webElementGuid>43686a60-37ff-4df2-ad42-7f6d6d8a4747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'ACCOUNT.2');</value>
      <webElementGuid>413db3d4-2914-4fcb-ba2e-2968f251795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('ACCOUNT.2')</value>
      <webElementGuid>cb424a0b-b39b-4530-826e-e9808591c8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:ACCOUNT.2&quot;)</value>
      <webElementGuid>4617b369-d1af-4d82-a4b0-54c517bda155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:ACCOUNT.2']</value>
      <webElementGuid>a8e86f85-48cc-4c09-9954-3a5842ab48c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[9]/td[3]/input</value>
      <webElementGuid>ddfd150b-6edf-4da0-bb63-e769fc4f2d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[3]/input</value>
      <webElementGuid>c23d2fc4-6356-4158-8f0c-dafdb49550d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:ACCOUNT.2' and @name = 'fieldName:ACCOUNT.2' and @type = 'text']</value>
      <webElementGuid>688a443b-db38-4344-af30-1107be904515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
