<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find</name>
   <tag></tag>
   <elementGuidId>72f0c87e-babb-4703-8beb-fd33dc749908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.textbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Find')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bbe9a9c-0e82-412b-827c-7df096e1891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Run Selection</value>
      <webElementGuid>f152a198-3721-4e33-8b35-e2acf7e0b5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Run Selection</value>
      <webElementGuid>618c0304-6b1c-4c65-a2a9-52522b57a922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbtn</value>
      <webElementGuid>f5f2e848-b64e-49e8-b9c8-dba8eb70eae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>63179f57-0b3f-4bc8-bad7-94d1a55d8d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>fdde4ba0-7073-4f29-84b4-8e5d43a3f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:
						   toggleStateButton();doEnquiry()</value>
      <webElementGuid>cf0dadf3-dbc8-4ee0-abd1-e92fd8033e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doHighlight(this);</value>
      <webElementGuid>4de91112-c8ce-44ca-b896-a1b80acba91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find</value>
      <webElementGuid>11e8b722-0701-4fa6-b7c9-9404c2c17318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqsel&quot;)/table[@class=&quot;enqsel-main enqsel-main_S3PASSBOOKREPRINT&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;display_box display_box_S3PASSBOOKREPRINT enqsel-selections enqsel-selections_S3PASSBOOKREPRINT&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;header-table header-table_S3PASSBOOKREPRINT&quot;]/tbody[1]/tr[@class=&quot;caption caption_S3PASSBOOKREPRINT&quot;]/td[3]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;textbtn&quot;]</value>
      <webElementGuid>5f5855e8-01bd-4e77-858a-5197d5b1ab44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td[3]/div/table/tbody/tr/td/a</value>
      <webElementGuid>e844548f-7b05-4d99-a0c4-e5852900c6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='doHighlight(this);']</value>
      <webElementGuid>e61ee8bc-491b-47a0-bb42-79b2e120617f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find')]</value>
      <webElementGuid>b9561ecc-4bb0-43c7-bb36-d49a9617f9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Selection'])[1]/following::a[1]</value>
      <webElementGuid>54c3f418-5929-40d4-a04e-5c7a817c3d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[1]/following::a[2]</value>
      <webElementGuid>fd59acb1-38a4-4f3b-8ec1-2ec2e8786253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::a[1]</value>
      <webElementGuid>ba1e73c3-8286-4339-9e82-c9811d0441a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find']/parent::*</value>
      <webElementGuid>cd4e0f94-233e-4502-a1a6-413b93b3715a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:
						   toggleStateButton();doEnquiry()')]</value>
      <webElementGuid>06e7c0a3-2149-4dc2-9399-c3501856e9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/a</value>
      <webElementGuid>c27f443c-eb63-4bf7-9019-b9f85b860193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@alt = 'Run Selection' and @title = 'Run Selection' and @href = 'javascript:
						   toggleStateButton();doEnquiry()' and (text() = 'Find' or . = 'Find')]</value>
      <webElementGuid>78cee58e-26d8-482e-adf2-3e128986913b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
