<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Authorize</name>
   <tag></tag>
   <elementGuidId>bf8a91cf-05aa-479b-b413-05e062a26f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Authorize&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Authorize']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>723ff4fa-47e7-4772-a424-3ff4cce3a49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/enquiry/drilldown/txnauthorise.gif</value>
      <webElementGuid>f6e3d5ce-871c-4d7b-bc0f-4a12da7f35bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Authorize</value>
      <webElementGuid>74616752-af3e-445c-9ddb-836b470d7f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Authorize</value>
      <webElementGuid>ca0e6370-df68-4792-9deb-279b9a9f5ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_S3PASSBOOKREPRINT&quot;]/a[1]/img[1]</value>
      <webElementGuid>e7f0163f-2250-4941-9e5a-99bc4566c773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[8]/a/img</value>
      <webElementGuid>06c2a70d-84fe-4ccd-8e31-ddfe38794e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Authorize']</value>
      <webElementGuid>67c735bb-a740-488b-8269-0ca3b360b141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a/img</value>
      <webElementGuid>f01ff53f-6b58-4c7c-8b77-21a8ddd5f1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/enquiry/drilldown/txnauthorise.gif' and @alt = 'Authorize' and @title = 'Authorize']</value>
      <webElementGuid>90f07128-115f-488e-842f-070b334be82b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
