<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_END.DATE</name>
   <tag></tag>
   <elementGuidId>f178c3c7-524b-4031-a1c2-f805fbb3a7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value:4:1:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea8b7936-4e59-49c6-89f7-09b20637c756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1ff8d81-9d7e-4d54-ae85-936a284254bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:4:1:1</value>
      <webElementGuid>cff7c8cd-0797-4bf1-9448-1fcb5f02f496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:4:1:1</value>
      <webElementGuid>5e4488f1-c564-468c-9fbc-1683be711162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e054d14e-9fa9-47c9-a350-ea50bfe1b69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:4:1:1</value>
      <webElementGuid>5ac3172a-2b34-4f1d-b4fc-fea5f8c6eda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_S3PASSBOOKREPRINT</value>
      <webElementGuid>9c529085-a6b8-4277-a308-6df5cf6fc452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:4:1:1&quot;)</value>
      <webElementGuid>f88d1027-f3a7-4062-bd18-e5a865a518b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr[4]/td[3]/input</value>
      <webElementGuid>c51a0c4d-ebb9-4f44-b9b2-cae45cc56d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value:4:1:1']</value>
      <webElementGuid>844d08ac-4c95-462b-b2c5-5ddabe506399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/input</value>
      <webElementGuid>9282d247-b6e9-4bfb-ac9a-2a13a28a62c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'value:4:1:1' and @id = 'value:4:1:1']</value>
      <webElementGuid>1d73ed18-c66e-445c-90f4-62f4941d4c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
