<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YESNO</name>
   <tag></tag>
   <elementGuidId>3198a323-6851-460a-b6be-83f9294dfc9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error_box']/table/tbody/tr[3]/td/table/tbody/tr/td[3]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4a73f6d-7683-4388-96ee-ad2754aa52cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>warningbox</value>
      <webElementGuid>459f5d01-37a5-4fcb-b056-17076d8759c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16e98f64-1d05-4da1-840c-99be71623247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warningChooser:Passbook Printed OK?</value>
      <webElementGuid>bb5ae3f8-1a56-4e18-b51f-0a7c6fc9f1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warningChooser:Passbook Printed OK?</value>
      <webElementGuid>57307bf3-ec79-4640-a44a-230d1f534678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>warningid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aa7e122b-0d12-46c0-ba05-ad23d3c5a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:changeWarning('warningCaption:Passbook Printed OK?', 'warningChooser:Passbook Printed OK?')</value>
      <webElementGuid>e805b760-83ee-4243-80c7-f310dafc286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YESNO</value>
      <webElementGuid>3d7be3a2-0921-468e-b383-d47de07e688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warningChooser:Passbook Printed OK?&quot;)</value>
      <webElementGuid>0b3cdb33-55db-4009-bb64-e82b35eb323e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr[3]/td/table/tbody/tr/td[3]/select</value>
      <webElementGuid>da231435-351b-4f32-83db-b02ce07c0860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='warningChooser:Passbook Printed OK?']</value>
      <webElementGuid>cb2c47e7-66f5-4a6f-ac74-36cf990c0da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passbook Printed OK?'])[1]/following::select[1]</value>
      <webElementGuid>245a3c01-c955-4a4b-8554-ff9ba10e48f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Balance: 0'])[1]/following::select[1]</value>
      <webElementGuid>3a961ea5-dede-4d2d-b0a5-eb4df2884b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page No'])[1]/preceding::select[1]</value>
      <webElementGuid>179ff55f-ce89-4236-896d-fdda8c4fcd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line No'])[1]/preceding::select[1]</value>
      <webElementGuid>3337be4f-8058-4fa9-a22b-799858546e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>96415f9b-1691-4b12-abf9-5e6fbb65e68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'warningChooser:Passbook Printed OK?' and @id = 'warningChooser:Passbook Printed OK?' and (text() = 'YESNO' or . = 'YESNO')]</value>
      <webElementGuid>84b6ad5c-b4b6-41f3-a660-8c8a44338a2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
