<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_NormalRisk</name>
   <tag></tag>
   <elementGuidId>5023da00-e8b5-4458-a4a8-3596dc21432a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='radio:tab1:CUSTOMER.RISK'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@selected = 'false' and @type = 'radio' and @id = 'radio:tab1:CUSTOMER.RISK' and @name = 'radio:tab1:CUSTOMER.RISK' and @checked = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d9467a4-3046-4f2e-a45f-c905fa67b8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_CUSTOMER radioCheckStyle_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>2b7a5bf7-772d-4d41-9fa0-15395b9bd3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e1f15a7-7cc5-419f-9649-0e51f6bdb697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>92e9e234-4580-45cb-82ef-98059d5143d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:toggleRadio(event)</value>
      <webElementGuid>fbdd662d-a3db-497e-bdf9-464b8b390541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>fe57c0b4-32e3-4a7a-9402-545a42407446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>1cbd6c53-0b60-4d4e-9462-0d6f454373c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb60391c-622a-4cf6-9a30-46ba7d78d603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>203d277c-d762-44ce-ae46-6cea5d95a1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>2e0f0f19-d8d9-4d48-80d0-f8226e896c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>1a518647-d164-458d-af5e-a8117468c490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b3df9cb8-ef7d-49ae-b5be-61e55f7e22ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
          javascript:clearEnrichment(event);
        </value>
      <webElementGuid>c2aaa6a2-fbc1-4009-a7b6-0077164d2409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'');</value>
      <webElementGuid>8d6e1067-b7b7-4981-83d5-1261fb523beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('')</value>
      <webElementGuid>93f32311-3873-4173-b852-607ea8ed6796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6dd61c4b-a3e5-4a1e-a8ac-1176dd750296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[16]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/input[@id=&quot;radio:tab1:CUSTOMER.RISK&quot;]</value>
      <webElementGuid>f7a62fd1-bdd4-4869-9b86-168376aeab4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[16]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>46b782dc-c98f-403a-aaea-007ee173399d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='radio:tab1:CUSTOMER.RISK'])[2]</value>
      <webElementGuid>7116957d-b8e8-4a99-9d17-74203792b87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e24e780c-307b-40ce-b72f-2e42ef78b0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'false' and @type = 'radio' and @id = 'radio:tab1:CUSTOMER.RISK' and @name = 'radio:tab1:CUSTOMER.RISK' and @checked = 'true']</value>
      <webElementGuid>a41cc547-8c41-4b0b-98bb-d5599da06d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
