<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_HighRisk</name>
   <tag></tag>
   <elementGuidId>15365eeb-03e2-4e58-ab94-772c36cb0c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio:tab1:CUSTOMER.RISK']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69d7e976-4d78-480b-8a69-a90fb67bcc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_CUSTOMER radioCheckStyle_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>02715757-b00a-420e-9278-b6248434a017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16cc4295-5791-4b00-8953-6b39b22bab04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>49522dd8-ec7e-4a40-9400-928c0120d8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:toggleRadio(event)</value>
      <webElementGuid>458960f4-8db0-408c-bb15-9a3ed48a8092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>e39c9fd3-1572-4ca0-becb-9d9f6fed77eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>c6e1ff90-fd5a-4ff8-a92b-0375e2c746f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cebe3c25-71ff-4743-9f3b-54729f09d1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4821afcb-15c8-430a-84e6-719761ec3373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>fda0f1e7-e23e-4d01-b182-fd185824d0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab1:CUSTOMER.RISK</value>
      <webElementGuid>fa8f2975-0bbe-4f2b-92fb-0f160315bd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c83cac4-48fd-402e-9fbb-75c239836d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
          javascript:clearEnrichment(event);
        </value>
      <webElementGuid>6cb09f48-4c87-421e-b6c6-fc09298fc3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'');</value>
      <webElementGuid>7c25824e-d2cd-4e62-8ad3-bb08e87cf20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('')</value>
      <webElementGuid>51cd0ab3-afb2-466b-9959-fdaf0a3b0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[16]/td[3]/table[1]/tbody[1]/tr[1]/td[1]/input[@id=&quot;radio:tab1:CUSTOMER.RISK&quot;]</value>
      <webElementGuid>2b75d4ee-e636-4d7e-84ad-5aad0e00888f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[16]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>3e1013c6-2aa1-4f17-be6e-fd8a237b6c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio:tab1:CUSTOMER.RISK']</value>
      <webElementGuid>6ac82fae-5fc8-465d-a747-54f8a45eee5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>8babc063-3f94-495d-8542-c2cbd9e84d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'false' and @type = 'radio' and @id = 'radio:tab1:CUSTOMER.RISK' and @name = 'radio:tab1:CUSTOMER.RISK']</value>
      <webElementGuid>a857e012-9a4d-403f-9a10-480b25e8f2a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
