<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectCustomerStatus</name>
   <tag></tag>
   <elementGuidId>047328af-5f3a-4544-af41-c8ad1660b2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:CUSTOMER.TYPE']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89b18884-1b2e-46f4-af28-0c0376c383fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>5ba76c0f-93a5-48f9-8190-daaaf05de03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CUSTOMER.TYPE</value>
      <webElementGuid>4532f05f-75ef-44ff-8263-a49b0b743b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CUSTOMER.TYPE</value>
      <webElementGuid>002a078f-0c8b-4e5c-a482-f8330363f625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56d2b593-8473-4d3c-8f70-6d29df8acb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>cf473348-aa3b-4feb-a97c-1ad4ad870bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>517cae4f-4350-46c0-a998-70403bcacbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_CUSTOMER.TYPE</value>
      <webElementGuid>97c2ba5c-d402-4c1d-99e8-98fbad79ab7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CUSTOMER.TYPE');</value>
      <webElementGuid>12709c59-de29-4597-abba-9ee5e45ce262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CUSTOMER.TYPE')</value>
      <webElementGuid>70aa817b-4d87-431d-b240-ee22aad44db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  ACTIVEEXTERNAL.USERPROSPECT</value>
      <webElementGuid>90bfa484-fae4-47f2-a756-dc5272d3d203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:CUSTOMER.TYPE&quot;)</value>
      <webElementGuid>1fc7576a-1f09-447d-9bb6-1fb7f0943177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[13]/td[3]/select</value>
      <webElementGuid>1bf7abf1-9f44-4a5b-a412-75035478aa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:CUSTOMER.TYPE']</value>
      <webElementGuid>d476982f-7d61-423f-8239-7bfbadbfd310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Type'])[1]/following::select[1]</value>
      <webElementGuid>97470394-54e8-4627-a530-9e2e137d3296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate-Small'])[1]/following::select[1]</value>
      <webElementGuid>c7be50f7-5734-4d1b-b242-589c165a1fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Rating.1'])[1]/preceding::select[1]</value>
      <webElementGuid>e5da0f9a-882a-4b9a-8f4d-1a25fb3ac117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Risk Rating'])[1]/preceding::select[1]</value>
      <webElementGuid>b9d87b20-bac7-48fc-a805-a254a9ac5f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>afd5549c-3002-482b-8b8e-3c720f60c0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:CUSTOMER.TYPE' and @id = 'fieldName:CUSTOMER.TYPE' and (text() = '  ACTIVEEXTERNAL.USERPROSPECT' or . = '  ACTIVEEXTERNAL.USERPROSPECT')]</value>
      <webElementGuid>80c620e4-91dd-48d1-b3a1-141aa7bd5b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
