<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RECEIVEDNOT RECEIVED</name>
   <tag></tag>
   <elementGuidId>82793f37-b656-4074-ab2b-a2297b979672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error_box']/table/tbody/tr[3]/td/table/tbody/tr/td[3]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>003a6af1-330a-4901-9bc3-9239218e44a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>warningbox</value>
      <webElementGuid>c2e8eebf-464b-460e-a0b8-ec0dc4b12baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a60e252-7407-4af3-a750-d9bb94fd274d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390</value>
      <webElementGuid>9b80dcdf-bc36-496b-893e-3c02a70e41c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390</value>
      <webElementGuid>612d5be5-f6ba-425f-a229-2aa43bb215eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>warningid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>28bdc584-14f0-4bd3-bc38-c47450bac1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:changeWarning('warningCaption:Have you received Acceptable ID.1/CUS*100 from 5179390', 'warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390')</value>
      <webElementGuid>000aef46-020c-40c0-8926-9a23887c4215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RECEIVEDNOT RECEIVED</value>
      <webElementGuid>a37db02f-12b3-4f8e-aef0-cf1618feb708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390&quot;)</value>
      <webElementGuid>23479dc8-2a96-4656-9b7d-3c6b5b1a046f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr[3]/td/table/tbody/tr/td[3]/select</value>
      <webElementGuid>b4af777e-4d25-437d-bd5b-e88e18da3796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390']</value>
      <webElementGuid>cdd7df66-aace-40f1-bceb-0af8e1c4efb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have you received Acceptable ID.1/CUS*100 from 5179390'])[1]/following::select[1]</value>
      <webElementGuid>7b9ae384-4c86-4ec5-b972-94ad8409d36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2004-LAS PINAS)'])[1]/following::select[1]</value>
      <webElementGuid>6ea4d77c-2b63-4e01-9643-20af49956f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have you received Acceptable ID.2/CUS*100 from 5179390'])[1]/preceding::select[1]</value>
      <webElementGuid>2d0abf8d-fba7-4ed8-b136-f3793275a717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept Overrides'])[1]/preceding::select[2]</value>
      <webElementGuid>81ecd70a-64ba-4209-a05e-011fa9cb56ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>df7a42b9-064b-47f6-ab19-41a38316dc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390' and @id = 'warningChooser:Have you received Acceptable ID.1/CUS*100 from 5179390' and (text() = 'RECEIVEDNOT RECEIVED' or . = 'RECEIVEDNOT RECEIVED')]</value>
      <webElementGuid>188de886-b060-44f7-9ca9-bb784a778b38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
