<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Authorize</name>
   <tag></tag>
   <elementGuidId>6aca2356-8c8b-443d-8974-eec5a93db5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Authorise&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Authorise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c278b948-a52b-4aec-a0f6-afcc93d9ff6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/enquiry/drilldown/txnauthorise.gif</value>
      <webElementGuid>2042d3cb-3a70-45db-9024-97d663649046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Authorise</value>
      <webElementGuid>dfcc2901-2908-4681-9556-9b743b47a5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Authorise</value>
      <webElementGuid>164d67ad-d4d3-4170-a3b6-0bb79392811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_EWBS3ENQCSHTXNNAU121&quot;]/a[1]/img[1]</value>
      <webElementGuid>c2ee079a-a43f-43fd-be99-a14593ca2826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[10]/a/img</value>
      <webElementGuid>fd267ece-ad33-4952-8000-d3ec838f04ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Authorise']</value>
      <webElementGuid>64f3c435-26c5-4085-baf7-3e2687fa664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/a/img</value>
      <webElementGuid>c1ba2ca5-1d53-462b-b828-4079752d9cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/enquiry/drilldown/txnauthorise.gif' and @alt = 'Authorise' and @title = 'Authorise']</value>
      <webElementGuid>13b75722-47d5-48c8-9dc4-38eaf0b874e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
