<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_2.2</name>
   <tag></tag>
   <elementGuidId>da3b6ff8-99f0-4612-8c53-c0907426e271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BLANK100355132601</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>a90c7dd2-d4e8-4e1f-813f-1f867700e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BLANK100355132601</value>
      <webElementGuid>96c1ec54-aa75-42db-8f51-06fda973af26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BLANK100355132601</value>
      <webElementGuid>d8151d27-f392-44c2-97b9-62d676503c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d4d3ce43-e40c-4702-b8b0-3aa5b4e00045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>e63a9453-519a-4027-b3f5-79bd9aa72854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BLANK100355132601&quot;)</value>
      <webElementGuid>0168cd5a-cb99-48bc-acdd-d25d1484040a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='BLANK100355132601']</value>
      <webElementGuid>7ed372ab-7cbf-4c06-88cf-a3cd69225a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>6bfc5b35-bfa7-4c89-b08f-315798fedaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'BLANK100355132601' and @name = 'BLANK100355132601' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>641bbb63-3de3-4da8-a211-f0c5f9168c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
