<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_BLANK066985070501</name>
   <tag></tag>
   <elementGuidId>3c3f188c-b908-4162-b95e-8501da3870cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BLANK066985070501</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@target='workarea']/../frame[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>0d5a6263-eccb-4926-9309-06a9da69171e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BLANK066985070501</value>
      <webElementGuid>17348a20-fbad-4b5f-af4f-2f01c2ab2859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BLANK066985070501</value>
      <webElementGuid>1b2ae9dc-8161-439f-bce6-a1dae0d233a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5522a433-9ed2-4f5e-b30f-24f55f861bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>d04695ea-5108-43bb-a2ce-6d805fdeb2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BLANK066985070501&quot;)</value>
      <webElementGuid>6f9c51d5-42a4-47e7-82b9-9bc0c958e0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='BLANK066985070501']</value>
      <webElementGuid>bed8395e-6ca4-4d71-8678-999b16e565e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>43e355db-3948-4ee5-bd85-2c5a38ee322c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'BLANK066985070501' and @name = 'BLANK066985070501' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>1917d191-c159-4368-9d2e-d9d59589e8fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
