<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Source of Funds</name>
   <tag></tag>
   <elementGuidId>f8877950-b9ac-42f9-aad3-98e5fea50837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b702bba6-859e-45a8-bab4-10f87c9b97bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>529e5be2-37da-44f4-a0bb-0262148e16d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>32d3ba91-d9cb-464f-ac5b-9a4768f55379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SOURCE.OF.FUNDS:1</value>
      <webElementGuid>ecb07db9-da37-4e34-812f-86a4454456d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>39983ec7-e4fb-4ade-9fe6-bb8f9d8f087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab5</value>
      <webElementGuid>cf513b0d-e629-4ecd-b3df-540356e2ed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>359a94fb-6057-4c6c-9b76-2eefa42d522d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event);</value>
      <webElementGuid>2ca35e30-18d0-4142-91af-0b55078326ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>ef37ab82-4376-479c-a8a6-ebbc2036b324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SOURCE.OF.FUNDS:1</value>
      <webElementGuid>9799b06b-9190-41b9-b5e1-e17c36dbbcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SOURCE.OF.FUNDS');</value>
      <webElementGuid>93818588-8c97-4924-a917-e3357c853ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SOURCE.OF.FUNDS')</value>
      <webElementGuid>73aeb9ca-1761-4d75-b29c-cff9d4378403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus</value>
      <webElementGuid>6f28bfe3-6c84-42fa-949e-7102386b3bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SOURCE.OF.FUNDS:1&quot;)</value>
      <webElementGuid>aa04b87f-8cf0-4d8a-b350-491e2290bdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Communication Details Tab/frame_Capture object_VERAMEND015155711901</value>
      <webElementGuid>81fb6c78-24a7-4127-8a29-74205a983e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab5']/tbody/tr/td[3]/select</value>
      <webElementGuid>ce37dba6-f130-4fde-8bca-f3dbdea184ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:SOURCE.OF.FUNDS:1']</value>
      <webElementGuid>4b04bdbe-20d3-4fa9-b792-ca22b383527f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source of Funds.1'])[2]/following::select[1]</value>
      <webElementGuid>2bcf54de-e286-4695-b2dc-98dbb537cae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Liability'])[1]/following::select[1]</value>
      <webElementGuid>feeddb2c-970c-4c47-b9cb-2fd623c413ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Size'])[1]/preceding::select[1]</value>
      <webElementGuid>22773dae-0f7f-46b2-91c0-037315d73d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Bank Accounts.1'])[1]/preceding::select[2]</value>
      <webElementGuid>247768e8-ca0f-40be-8df8-345f95672c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[3]/select</value>
      <webElementGuid>678b8880-91e7-4e44-a915-836d9f884ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:SOURCE.OF.FUNDS:1' and @id = 'fieldName:SOURCE.OF.FUNDS:1' and (text() = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus' or . = '  AllowanceBusiness IncomeDividendsDonationGiftInheritanceInvestment InterestLottery WinningsPersonal SavingsRemittanceRetirement/separationSalary/benefitsSale Of AssetsTrust FundsAverage OvertimeCommissionEcolaGuaranteed BonusPensionPera(govt Employee)Professional FeesRata(govt Employee)Variable Bonus')]</value>
      <webElementGuid>a60622d8-708e-4233-9c7b-f342e7346fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
