<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Products</name>
   <tag></tag>
   <elementGuidId>31b6894a-430e-4ca4-b7d0-fcf4aaa58020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[contains(@id, 'Products')] </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Products101335339604</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>6f12449a-5649-4863-93e9-b12d0e3a7e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>aa835495-4c67-4218-9995-88d156662958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Products101335339604</value>
      <webElementGuid>5932ad22-b822-4378-92c9-1e100e03114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Products101335339604</value>
      <webElementGuid>3fb37119-1e76-4d92-9ed5-b10db62adc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b94b54cd-4533-46aa-9a57-d43525865c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/product/blank.htm</value>
      <webElementGuid>badbcddd-90b2-481b-aa94-d678825a29d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Products101335339604&quot;)</value>
      <webElementGuid>2c9ddaef-dc97-4138-b1e0-fcffa16827ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='Products101335339604']</value>
      <webElementGuid>2c0e0e47-3f8a-437e-9e0a-3bea66c659e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame[2]</value>
      <webElementGuid>b6e94eaa-ebe1-4d96-8a29-fa3c2005fe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'Products101335339604' and @name = 'Products101335339604' and @src = '../html/product/blank.htm']</value>
      <webElementGuid>c913db98-fbea-4abc-8f71-2b1b70b81522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
