<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_VERAMEND100455493601</name>
   <tag></tag>
   <elementGuidId>e7dd0d8b-f9e5-46bf-95b0-b35cdfd19839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VERAMEND100455493601</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>6a638e69-9156-4f01-9da5-36d3537d189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VERAMEND100455493601</value>
      <webElementGuid>fc3d582a-94f6-477e-8753-79dae678308f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VERAMEND100455493601</value>
      <webElementGuid>486b4e4d-72aa-449e-8b08-e60aa8331b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>eecc7bde-da9d-4afa-9761-70eb188eb3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>1e5c3edc-f3ef-4732-9f0d-babcdb552b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VERAMEND100455493601&quot;)</value>
      <webElementGuid>107e26c9-1509-4741-bcee-254259691b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='VERAMEND100455493601']</value>
      <webElementGuid>010765f3-5f88-4c4c-95a1-334ec085a250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>67b72306-769e-469b-887b-4e838ba51c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'VERAMEND100455493601' and @name = 'VERAMEND100455493601' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>b68409ac-65d6-41aa-a336-bd888baaeaec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
