<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country</name>
   <tag></tag>
   <elementGuidId>8de6a390-f01f-4ab6-85d3-e56a104c506b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:COUNTRY:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3c436a8-6140-4fbb-bd96-7f494bc971a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c60e28f9-73cb-4711-8ad3-d4a17ef0ae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>f49b668c-b538-4d2e-b02d-bb29e390cc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:COUNTRY:1</value>
      <webElementGuid>4417fd3b-3500-4b68-8050-51b23319d594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:COUNTRY:1</value>
      <webElementGuid>7c422219-b072-4bd1-967f-1ed21ddbaefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab2</value>
      <webElementGuid>0eea76e8-95d0-4248-b967-eebd232b2d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PH</value>
      <webElementGuid>b634d75f-f2ff-4090-89ec-9baa22276ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>PH</value>
      <webElementGuid>2c833b7d-744d-47a3-8a76-5e763ecb400d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3INPUT</value>
      <webElementGuid>21d62a1d-694c-45b0-92cd-d7378ea5ac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>91bf0ab8-dfd9-4eaf-9941-bce71ed2eb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ccf8681-9929-48c1-ac7c-10db7b83b671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdown</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>88dcda79-cdb0-4785-8076-d53879dfb939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lng</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>3206cbcc-fa8c-42c3-9209-005044c7b580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>b0fe9a34-84f0-4e73-a6bf-5b8714a9f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event); doFieldChangeEvent(event);</value>
      <webElementGuid>a719a8ea-c278-4d3c-bd9a-1ac0d3a982b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>850d802c-97c5-4e43-9339-87fa8b476ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>87aafaf9-8966-4336-82ba-8a23477132ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'COUNTRY');</value>
      <webElementGuid>ccfc4728-b6f2-4ff8-8930-530c152f7db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('COUNTRY')</value>
      <webElementGuid>08b13647-f8c7-4ca2-9c4f-e2572937a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:COUNTRY:1&quot;)</value>
      <webElementGuid>865bca4d-6735-4b6b-9c88-180013f10842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer IND/Address_Tab/frame_Capture object_VERAMEND100455493601</value>
      <webElementGuid>4702bdf8-b8e8-46c3-af5e-3084e548cabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[7]/td[3]/input</value>
      <webElementGuid>04b06e5c-0a93-4886-acae-cc9e0376b474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:COUNTRY:1']</value>
      <webElementGuid>003e6e4e-693b-4f70-b4ea-5d0407bfd684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[7]/td[3]/input</value>
      <webElementGuid>5c0d039c-eee4-4c24-9e08-5a688c350be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:COUNTRY:1' and @name = 'fieldName:COUNTRY:1' and @type = 'text']</value>
      <webElementGuid>5dd7dee9-76a6-47d0-84e0-c0e07af225a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
