<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ValidateDeal</name>
   <tag></tag>
   <elementGuidId>c0b18f63-169a-4e2a-a552-c02f5b4d0d6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Validate a deal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Validate a deal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4679c18-f8ea-41cb-9d76-ed5f3bf427ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/default/tools/txnvalidate.gif
															</value>
      <webElementGuid>7801d23c-6664-4f50-a312-bb58a52e9121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Validate a deal</value>
      <webElementGuid>0dbe16ab-0413-4ad4-8ff8-391f9d335afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Validate a deal</value>
      <webElementGuid>92d7a192-ab0d-4086-95fd-19d1f3d3bc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]/img[1]</value>
      <webElementGuid>ef85f62b-52ef-46b3-a72c-dd468bff98bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/div/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>e424e965-86a4-467f-8c8b-16fc198d7a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Validate a deal']</value>
      <webElementGuid>17bf81df-ff5f-43f5-af27-a0eceb922f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/img</value>
      <webElementGuid>b0288ef1-26b8-4c6e-9a9d-56f515ecaa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/default/tools/txnvalidate.gif
															' and @alt = 'Validate a deal' and @title = 'Validate a deal']</value>
      <webElementGuid>a47904f9-ce14-4e93-a36d-db2a03f509aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
