<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArrangementID</name>
   <tag></tag>
   <elementGuidId>3f2cd263-21de-4d0f-ae9c-1d01b3274836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#disabled_ARRANGEMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27bf6db5-3199-4da5-aa06-60391e040e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>disabled_ARRANGEMENT</value>
      <webElementGuid>1f201596-65ad-4776-92b0-75dab73d7f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled_dealbox disabled_dealbox_AAARRANGEMENTACTIVITY disabled_dealbox_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>8afed7ad-0f53-4ccc-a63e-af57e116407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AA21154TTR7S</value>
      <webElementGuid>34cd4d0e-772a-4417-bef8-cd154e3a6c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disabled_ARRANGEMENT&quot;)</value>
      <webElementGuid>e90bc56c-7626-47aa-8c84-82d0e2ecd33c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[3]/span</value>
      <webElementGuid>d26a753f-522d-424f-9e4f-709f4ab5ac17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='disabled_ARRANGEMENT']</value>
      <webElementGuid>2ef28874-adae-422a-a159-8dd3e39f38ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrangement'])[1]/following::span[1]</value>
      <webElementGuid>3a778beb-4ae5-4c45-8e48-17ed44ff7b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit'])[1]/following::span[1]</value>
      <webElementGuid>02ed1275-566d-4d73-9563-481f1b69aafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/preceding::span[1]</value>
      <webElementGuid>d11a31f2-e6d1-4931-bd5e-e027fb1d3b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IU BLUE'])[1]/preceding::span[2]</value>
      <webElementGuid>498249e4-7beb-4258-bd06-25b616f1e0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AA21154TTR7S']/parent::*</value>
      <webElementGuid>c91c0b59-dfe6-43dd-9e82-347108f0714c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>76ac8a95-2bd8-4789-a2d2-b11d1bb06fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'disabled_ARRANGEMENT' and (text() = 'AA21154TTR7S' or . = 'AA21154TTR7S')]</value>
      <webElementGuid>1f9832ff-1eb7-4ee5-b0ca-572eb7f0b786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
