<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputShortTitle</name>
   <tag></tag>
   <elementGuidId>e01d66f5-210a-4a0b-823e-fce5ae55fe8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='tab1']/tbody/tr/td[7]/input)[@id='fieldName:SHORT.TITLE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76182060-2223-4fa4-b6a2-0a930b712da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac756fc7-b923-46da-affb-30a9c31c5650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>df3d7819-f1b7-454a-9f31-cc61b896aea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SHORT.TITLE</value>
      <webElementGuid>c5098d77-206e-4dbf-b930-6136be0f5beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SHORT.TITLE</value>
      <webElementGuid>f507dcf3-e946-41dc-b8c5-86fc318ec098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>3245a301-e669-49b3-b685-5c5496ff603f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_AAARRANGEMENTACTIVITY dealbox_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>1fff1671-28d4-4adb-8909-acab4a7b6077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>6ecd599f-b2af-4d3a-8450-9b7cbc0c9600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f7e6f70-4330-45f7-b61c-97a38123328f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>b50b942b-6ad9-4df0-815e-1b3730bf0c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SHORT.TITLE</value>
      <webElementGuid>ce39ca94-81b2-41be-bffd-33df3d0eb783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SHORT.TITLE');</value>
      <webElementGuid>3f49bd92-a807-44f4-a416-bdba7914dae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SHORT.TITLE')</value>
      <webElementGuid>e4994236-aed4-4d64-a834-8cfc0bf64a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SHORT.TITLE&quot;)</value>
      <webElementGuid>d9230455-96af-4914-91dc-7ec262b01e1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='tab1']/tbody/tr/td[7]/input)[4]</value>
      <webElementGuid>d49ba189-2abb-439f-914a-3d091f3d2c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:SHORT.TITLE']</value>
      <webElementGuid>321cf972-553e-4466-b22f-d8e811fb7c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/form/div[3]/table/tbody/tr[2]/td/table/tbody/tr/td[7]/input</value>
      <webElementGuid>547092a3-3345-43cd-891b-e4bec221929b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:SHORT.TITLE' and @name = 'fieldName:SHORT.TITLE' and @type = 'text']</value>
      <webElementGuid>615d3c92-3bef-4816-a3f3-c025b47a11bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
