<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCustomer</name>
   <tag></tag>
   <elementGuidId>a7c2ef02-e2eb-4c3a-99b8-fb86ae0db0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fieldName:CUSTOMER' and @name = 'fieldName:CUSTOMER' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr/td[7]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cb15e4a-273c-44b2-9421-45d93a950f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cfdc40c-6a3d-4493-9e45-7512583797a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>35048755-7fdb-4a8a-87d2-c4c34b69aee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CUSTOMER</value>
      <webElementGuid>dc89b61e-315a-4155-8bbe-3e8201f45db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CUSTOMER</value>
      <webElementGuid>4aae026a-1ec5-410e-a5ac-1d6c6d8a2e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>fb0e6d6d-878c-4dd0-842b-6bbaa3009102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_AAARRANGEMENTACTIVITY dealbox_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>36329f1c-2f73-4bd3-aeb8-046f867e63d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cfef6164-979d-4187-ad0c-5ddb5a391201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df2d9cb2-2b50-4de1-8e44-b5b40eeb8784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdown</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>aa6e5a8a-0919-4d62-90e1-444065da8051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>e3413d8a-c020-42b7-8e52-7040cbb040e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_CUSTOMER</value>
      <webElementGuid>dd263296-e0ea-4bed-9062-a265cd4dcfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CUSTOMER');</value>
      <webElementGuid>e11b130e-8781-4f83-a90e-84e49b54fefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CUSTOMER')</value>
      <webElementGuid>9c0230f2-4091-41f1-af25-1f5a62bc1b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:CUSTOMER&quot;)</value>
      <webElementGuid>01f2b6a4-901d-4915-95a5-c0a504e89345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[7]/input</value>
      <webElementGuid>b1b93b56-e457-4e86-8f82-e1d26ee4a56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:CUSTOMER']</value>
      <webElementGuid>59f79f71-c4e9-4bf4-889a-c8d965fa6a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>269d1f90-b5d4-43ab-a6e5-57afcc17cc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:CUSTOMER' and @name = 'fieldName:CUSTOMER' and @type = 'text']</value>
      <webElementGuid>11823da2-8fa5-4658-84a7-fa9339999266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
