<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelProduct</name>
   <tag></tag>
   <elementGuidId>b0247e22-66d0-4cc2-b76b-8e527d50c5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[2]/td[3]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'SDA Regular' or . = 'SDA Regular')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c62b2301-cd79-4522-a17b-b68be61ee3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled_dealbox disabled_dealbox_AAARRANGEMENTACTIVITY disabled_dealbox_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>4db4f6fe-e21d-4839-93a7-077693422175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SDA Regular</value>
      <webElementGuid>e94399e3-7a58-4411-af24-25939deeaad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[2]/td[3]/span[@class=&quot;disabled_dealbox disabled_dealbox_AAARRANGEMENTACTIVITY disabled_dealbox_AAARRANGEMENTACTIVITY_AANEW&quot;]</value>
      <webElementGuid>793486e9-e6f9-486f-95a2-fcb65339dd73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[2]/td[3]/span</value>
      <webElementGuid>b5271c4c-6c63-4324-8e5a-33c90fd60421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::span[1]</value>
      <webElementGuid>19ddf80b-939d-4f73-a912-780f1bcc90e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::span[2]</value>
      <webElementGuid>5a6fb950-bea2-437e-85bd-be80c694defe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variation'])[1]/preceding::span[2]</value>
      <webElementGuid>7f81e9c8-23c5-403b-9613-0586c8783969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::span[2]</value>
      <webElementGuid>8620bb31-b349-4339-b4e0-2c244c35e5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SDA Regular']/parent::*</value>
      <webElementGuid>1ac1e006-1e17-4d07-80af-3c0a273a5055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/span</value>
      <webElementGuid>41ae4043-0f82-40f0-a7ae-2919ad2647c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SDA Regular' or . = 'SDA Regular')]</value>
      <webElementGuid>6b4c3bff-05b6-422f-91d7-f12f8945ff0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
