<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelShortName</name>
   <tag></tag>
   <elementGuidId>d43c6761-1c37-41d7-ba04-4395864e245f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enri_CUSTOMER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr/td[8]/span[@id='enri_CUSTOMER']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'enri_CUSTOMER' and @name = 'enri_CUSTOMER' and (text() = 'IU BLUE' or . = 'IU BLUE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ec98155a-9dc2-46df-adc1-9a4dea45090d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enrichment enrichment_AAARRANGEMENTACTIVITY enrichment_AAARRANGEMENTACTIVITY_AANEW</value>
      <webElementGuid>598cccc6-5e60-458f-84d8-353539bc9ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enri_CUSTOMER</value>
      <webElementGuid>6d3bae76-0338-48a4-b310-a75aed71e421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enri_CUSTOMER</value>
      <webElementGuid>d8e7a82d-cc08-4c6d-837d-2aa0b70dce1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IU BLUE</value>
      <webElementGuid>268123bf-224e-493e-9c32-162581761b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enri_CUSTOMER&quot;)</value>
      <webElementGuid>82d4f3b0-296a-4bd2-873e-1f9d15c388fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[8]/span</value>
      <webElementGuid>09984bab-0066-46fd-a0cb-42183ef6d90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='enri_CUSTOMER']</value>
      <webElementGuid>072838b3-7cac-4408-8013-a35145e01040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::span[2]</value>
      <webElementGuid>21024979-3edd-4558-80b3-5855662ca3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA21154TTR7S'])[1]/following::span[2]</value>
      <webElementGuid>66eea054-b278-47df-8ea4-aaeece73100b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::span[1]</value>
      <webElementGuid>1cc5e5b9-bb7c-4125-84da-22458b12ddd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDA Regular'])[1]/preceding::span[1]</value>
      <webElementGuid>7239a725-4ff8-40ab-a937-8574dde082ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IU BLUE']/parent::*</value>
      <webElementGuid>0e9b1e8e-965d-405c-9131-40c079e018fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span</value>
      <webElementGuid>7818e084-c6bc-4597-8cca-307f929ca367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'enri_CUSTOMER' and @name = 'enri_CUSTOMER' and (text() = 'IU BLUE' or . = 'IU BLUE')]</value>
      <webElementGuid>6418c5d5-38e5-4bff-9cb7-a14a5a0b8eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
