<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_VERAMEND100453869301</name>
   <tag></tag>
   <elementGuidId>c585897d-3775-4a94-9dd9-efc72c556a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VERAMEND100453869301</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>d717aada-173d-416d-a9f2-d8e5c343679e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VERAMEND100453869301</value>
      <webElementGuid>dadb5e0f-22f6-4f75-a874-b1e33c9f1d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VERAMEND100453869301</value>
      <webElementGuid>1f04e465-ef0f-470f-8d24-b206e9963822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3766d088-10a2-4f1a-bbb1-75371a644aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../html/blank_enrichment.html</value>
      <webElementGuid>db2099cf-5b07-4a44-8aa5-4078f6e0c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VERAMEND100453869301&quot;)</value>
      <webElementGuid>340a54a8-7f9b-4571-9aa4-bf6f07a7030f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='VERAMEND100453869301']</value>
      <webElementGuid>6e89bf34-7f53-4f61-a50d-205f2731968b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>1ab63ae0-6144-4474-8044-db70f824ec49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'VERAMEND100453869301' and @name = 'VERAMEND100453869301' and @src = '../html/blank_enrichment.html']</value>
      <webElementGuid>e1699945-dbb7-49b6-974a-70f26963141a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
