<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Risk Code</name>
   <tag></tag>
   <elementGuidId>8ea6438c-2b54-4e97-b92b-336c2faa7a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:CALC.RISK.CLASS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c94be7a9-7195-4334-bc8c-ea3399ad7870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0edfccc-a5cf-4c3c-a2a8-111e34d13092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6bc23894-c024-4911-a6db-21975e7da571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CALC.RISK.CLASS</value>
      <webElementGuid>5ec0de47-b3b8-43c8-9453-93904fceb412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CALC.RISK.CLASS</value>
      <webElementGuid>c4aeb340-ed30-4036-90c1-801821e60c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>55b549da-7fa5-436e-825c-86da919723d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>930b1734-9dfe-4617-afa4-001ca6d9ad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0b200570-e9e6-4af7-9bf8-357aacf246b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>2f5dcc74-a692-4b40-9b8a-6b9413c6039f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>be74e724-7570-438c-a29d-4685f68e75bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f41d59fa-9f75-4e75-909a-24ed98f7281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdown</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>b78bfbbc-1a12-46a7-bbe8-06d0a465501c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>412ace8a-0ff0-4b82-aade-43937262cb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event); doFieldChangeEvent(event);</value>
      <webElementGuid>de96b066-dd3d-4442-9f2d-6733b0a3c6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>6cf8c4fc-ad40-4a3d-86ac-050e7ced10d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>c6415357-937f-49ca-a01c-7246b722546c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CALC.RISK.CLASS');</value>
      <webElementGuid>730f0a3a-afb7-4d4d-a6f4-998c18fb30f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CALC.RISK.CLASS')</value>
      <webElementGuid>f628e680-b565-437b-a6ec-fb0b8aee89a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[18]/td[3]/input[@id=&quot;fieldName:CALC.RISK.CLASS&quot;]</value>
      <webElementGuid>87749b0e-da42-41c0-8377-cdfe49e4155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Customer Tab/frame_Capture object_VERAMEND100453869301</value>
      <webElementGuid>1fec481c-ddf0-47bb-aaca-844085bf4b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[18]/td[3]/input</value>
      <webElementGuid>3b9469c7-e626-4b3e-9830-69ded2571789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:CALC.RISK.CLASS']</value>
      <webElementGuid>e74b7b11-b5f0-4aaa-956b-3cf1067e0d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[3]/input</value>
      <webElementGuid>f3faeb9d-ddb9-40d7-ade9-54d82fbc6baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:CALC.RISK.CLASS' and @name = 'fieldName:CALC.RISK.CLASS' and @type = 'text']</value>
      <webElementGuid>f20fa51a-6576-4910-bef1-142ede8923c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
