<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Name</name>
   <tag></tag>
   <elementGuidId>fac3e8d4-4c02-4e43-975c-858e3a5da5cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:NAME.1:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ede243c1-2d98-4bd8-96da-e795a0eaa692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec1ff5c3-eae4-4729-a3c0-2e666d93fa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value> 35</value>
      <webElementGuid>065c14cc-9ec4-4b93-a1c3-cf720bf894b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:NAME.1:1</value>
      <webElementGuid>637f5872-8c35-4adb-a21f-c83a5ba7d70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:NAME.1:1</value>
      <webElementGuid>192a687c-98b1-4e51-ab5b-992deb7c7c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>1c236971-bf79-4a43-982e-58dbe0376754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LABA DABA DOO SERVICES 2</value>
      <webElementGuid>4bc0b168-0729-4c39-97cf-1b41d03132f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>LABA DABA DOO SERVICES 2</value>
      <webElementGuid>8dfd8815-6918-4a3e-84e5-cbed8e220cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_CUSTOMER dealbox_CUSTOMER_EWBS3CORP</value>
      <webElementGuid>082b9b55-2968-4b33-94f4-7d456d6cfc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value> 35</value>
      <webElementGuid>f5b64cf0-1286-42ef-b5a5-f1a507fbc6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f1a47fa-23a7-4828-8c89-9571a7612441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lng</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>897c6081-5daf-4643-ba25-450c107400bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>caseconv</name>
      <type>Main</type>
      <value>UPPERCASE</value>
      <webElementGuid>de949521-0a55-4afa-b93e-0b739e23278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler( event); doFieldChangeEvent(event);</value>
      <webElementGuid>1910f186-93de-4f24-b95d-958b51fd99ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>8450b834-8679-4976-ab8e-dcef2de6125e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>9b23411b-fea8-4932-abae-9c8afad4db85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'NAME.1');</value>
      <webElementGuid>80949087-091e-40fd-a47f-40e3170048d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('NAME.1')</value>
      <webElementGuid>a8c91b07-9b51-4eae-a50d-efe7a94a8acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:NAME.1:1&quot;)</value>
      <webElementGuid>b3c6cbbb-2e2f-4170-bfe6-b11c80f71e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Teller Screen/Customer/Amend Customer CORP/Customer Tab/frame_Capture object_VERAMEND100453869301</value>
      <webElementGuid>3f5e1879-b23d-45e4-8ebe-457a94f04a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>45b96000-c60a-4a7e-b5b4-64af88ee0b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:NAME.1:1']</value>
      <webElementGuid>3047882e-9ef3-4aa0-9d33-7cf03e691ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>930f2c75-c694-4877-ab66-53b6904a390f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:NAME.1:1' and @name = 'fieldName:NAME.1:1' and @type = 'text']</value>
      <webElementGuid>b8424a53-ed53-414c-b986-beda716d36d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
