<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_banner</name>
   <tag></tag>
   <elementGuidId>e09aae3e-1989-4d2c-9544-680ad0940ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[contains(@id, 'banner')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#banner100064972400</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>1192828b-4d14-46cb-9b1d-fc2f9136eb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banner100064972400</value>
      <webElementGuid>93ed7420-34e1-4f79-a5ec-0c23262257f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>banner100064972400</value>
      <webElementGuid>8385fc48-72f3-4f4b-bbf9-87aa644cef9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2387315f-4ed9-450e-b8da-a75b11810957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=BANNER&amp;skin=default&amp;compId=PH0022004&amp;usrRole=&amp;compScreen=COMPOSITE.SCREEN_EWB00975_100064972402&amp;contextRoot=&amp;windowName=banner100064972400&amp;user=EWB00975&amp;WS_replaceAll=&amp;WS_parentComposite=null</value>
      <webElementGuid>4f6e79ff-40ca-4baf-918f-a91b5326cf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner100064972400&quot;)</value>
      <webElementGuid>cfcc948a-7895-4878-97c6-ed995aae5a31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='banner100064972400']</value>
      <webElementGuid>53a5ea71-8c1b-44f3-87ca-e4e59a9f974a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>9a88dd06-c6e3-4a60-8ecf-b29d41542d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@id = 'banner100064972400' and @name = 'banner100064972400' and @src = '../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=BANNER&amp;skin=default&amp;compId=PH0022004&amp;usrRole=&amp;compScreen=COMPOSITE.SCREEN_EWB00975_100064972402&amp;contextRoot=&amp;windowName=banner100064972400&amp;user=EWB00975&amp;WS_replaceAll=&amp;WS_parentComposite=null']</value>
      <webElementGuid>dc1af43f-a94c-46ea-8465-b0165e071931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
