<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCommand</name>
   <tag></tag>
   <elementGuidId>9b6cd7e9-b02b-4e99-a5e6-0ed65fadf4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='commandLineForm']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#commandValue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'commandValue' and @id = 'commandValue' and @ref_element = 'Object Repository/3_Page_Input Command Value/frame_Capture object_banner100064972400']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e998eafe-7049-4b8b-ad25-e8a2ddbed7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commandValue</value>
      <webElementGuid>aa59e6a8-32fa-4472-935f-4ddcbb359ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commandValue</value>
      <webElementGuid>ae035495-864c-46d4-bcc6-ecf2c81e4ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>e46684e8-4b2d-41ac-b1dd-446097172e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e4706e6-950f-4cb6-9a27-c5ac6618411d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commandValue&quot;)</value>
      <webElementGuid>734f007b-5543-49f3-94c1-702e90fe3b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/3_Page_Input Command Value/frame_banner</value>
      <webElementGuid>d81e98ec-4673-4e6c-9908-fff1b86fb72d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commandLineForm']/input</value>
      <webElementGuid>27b2cac9-43af-4ca2-a331-487a4db3d18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='commandValue']</value>
      <webElementGuid>f7a9cadb-8382-4618-8fdc-d7b69e13a7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>16a9ad66-6e76-4a3f-908a-ade5f6fe2d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'commandValue' and @id = 'commandValue']</value>
      <webElementGuid>a8c80dd9-6b4b-4873-afbd-af98b6f6b53b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
